import type { ChapterInput } from '@/domain/chapter';
import type { Condition } from '@/domain/conditions';

const flag = (name: string): Condition => ({ type: 'flag', flag: name });
const not = (condition: Condition): Condition => ({ type: 'not', condition });
const all = (...of: Condition[]): Condition => ({ type: 'all', of });
const storm = (option: string): Condition => ({
  type: 'choiceMade',
  choice: 'choice-storm',
  option,
});
/** The afternoon, before the boats put out. */
const DAY = not(flag('evening'));
/** Back on the shore after the storm. */
const NIGHT = flag('returned');

type Entity = ChapterInput['scenes'][number]['entities'][number];

const look = (
  id: string,
  label: string,
  clue: string,
  text: string,
  x: number,
  y: number,
  sprite: string,
): Entity => ({
  id,
  kind: 'clue',
  label,
  x,
  y,
  sprite,
  interaction: {
    verb: 'examine',
    effects: [
      { type: 'discoverClue', clue },
      { type: 'showMessage', text },
    ],
  },
});

/**
 * The fishing quarter at Capernaum, on the north-west shore of the lake.
 * A fictional composite (record rec-recon-shore): basalt houses above a
 * pebbly beach, nets and fish-drying racks, a salter's tubs, boats drawn
 * up, and a stone jetty where the family boat is moored. In the afternoon a
 * crowd sits along the beach listening to the teacher speaking from a boat
 * offshore (Mark 4:1). The same place, at night, shows how your choices
 * came home with you.
 */
export const CAPERNAUM_SHORE: ChapterInput['scenes'][number] = {
  id: 'capernaum-shore',
  name: 'The shore at Capernaum',
  kind: 'outdoor',
  description:
    'A fishing quarter of dark stone houses above a pebbly beach. Nets hang to dry, fish lie on racks, and a stone jetty runs out into the lake.',
  layout: [
    'P,^^^^^^^^^,,F,^^^^^^^^^^,,P,,^^^^^^^^^,,F,P',
    ',,^^^^^^^^^,,,,^^^^^^^^^^,,,,,^^^^^^^^^,,,,,',
    'F,####D####,P,,####D#####,T,,,####D####,,P,,',
    ',,jb.....b,,,,,c.......jj,,,,,,.......bk,,,,',
    '============================================',
    ',l,,,,,,..,,,b,,,,,.....,,,,,,,,c,..,,,,,,F,',
    ',NN,,NN,..,,o,,,,,,.....,,RR,RR,,j,..,,,,,,,',
    ',,,,,,,,..,,b,,,,,,.....,,,,,,,,,jjk..,,F,,,',
    ',NN,,NN,..,,,,,,,,,.....,,RR,RR,,hh...,,,,,P',
    ',,,,,,,,......,,c,,.....,b,,b,,,,.....,,,,,,',
    ',r,,,,,,,,,,..,,,,,.....,,,,,,,,......,,,,,,',
    'e,,,,,,,,,,,..,,,,,.....,,,,,,,,,,,,,,,,,,,,',
    'ee:::::::::::::::::.....:::::::::::::::::::,',
    'ee:::::::::::::::::JJJ::::::::::::::::::::::',
    'ee::::::BBBB:::::::JJJ::::::::::::::::::::::',
    'e~:BBB:::::::::::::JJJ::::::::::::::::BBB:::',
    '~~:::::::r:::::::::JJJ:::::::::::::::::::r::',
    '~~~~~~::::::::::~~~JJJ~~~~::::::::::~~~~~~~~',
    '~~~~~~~~~~~~~~~~~~~JJJ~~~~~~~~~~~~~~~~~~~~~~',
    'LLL~~~~~~~~~~~~~~~~JJJ~~~~~~~~~~~~~~~~~~~LLL',
    'LLLLLL~~~~~~~~~~~~~JJJBBBBBB~~~~~~~~~~~LLLLL',
    'LLLLLLLLL~~~~~~~~~~JJJBBBBBB~~~~~~~~LLLLLLLL',
    'LLLLLLLLLLLLL~~~~~~JJJ~~~~~~~~~~BBBBLLLLLLLL',
    'LLLLLLLLLLLLLLLL~~~JJJ~~~~LLLLLLBBBBLLLLLLLL',
    'LLLLLLBBBBLLLLLLLLLJJJLLLLLLLLLLLLLLLLLLLLLL',
    'LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL',
    'LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL',
    'LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL',
  ],
  legend: {
    '#': 'wall',
    '^': 'roof',
    D: 'door',
    '=': 'paving',
    '.': 'sand',
    ',': 'scrub',
    ':': 'shingle',
    '~': 'shallows',
    L: 'lake',
    J: 'jetty',
    B: 'boat',
    N: 'nets',
    R: 'rack',
    j: 'jars',
    k: 'sacks',
    b: 'basket',
    c: 'crate',
    h: 'trough',
    o: 'oven',
    l: 'fence',
    r: 'rock',
    e: 'reeds',
    P: 'palm',
    F: 'fig',
    T: 'olive',
  },
  baseTile: 'scrub',
  spawns: {
    'from-house': { x: 6, y: 3, facing: 'down' },
    'from-lake': { x: 20, y: 20, facing: 'up' },
  },
  entities: [
    // ── The family ───────────────────────────────────────────────────────
    {
      id: 'elazar',
      kind: 'npc',
      label: 'Uncle Elazar',
      characterId: 'elazar',
      x: 21,
      y: 21,
      facing: 'right',
      interaction: { verb: 'talk', dialogue: 'd-elazar' },
    },
    {
      id: 'tamar',
      kind: 'npc',
      label: 'Tamar',
      characterId: 'tamar',
      x: 17,
      y: 13,
      facing: 'down',
      interaction: { verb: 'talk', dialogue: 'd-tamar' },
    },
    {
      id: 'sail-mending',
      kind: 'feature',
      label: 'Nets and gear waiting on the beach',
      sprite: 'net-pile',
      x: 16,
      y: 13,
      visibleWhen: DAY,
    },
    {
      id: 'yoezer',
      kind: 'npc',
      label: 'Yoezer the hired man',
      characterId: 'yoezer',
      x: 24,
      y: 13,
      facing: 'left',
      interaction: { verb: 'talk', dialogue: 'd-yoezer' },
    },
    {
      id: 'family-boat',
      kind: 'feature',
      label: 'The family boat',
      sprite: 'none',
      x: 22,
      y: 20,
      interaction: { verb: 'use', dialogue: 'd-boat' },
    },
    // ── Reading the sky ──────────────────────────────────────────────────
    {
      id: 'hanina',
      kind: 'npc',
      label: 'Old Hanina',
      characterId: 'hanina',
      x: 19,
      y: 24,
      facing: 'down',
      pose: 'sit',
      visibleWhen: DAY,
      interaction: { verb: 'talk', dialogue: 'd-hanina' },
    },
    {
      id: 'lake-view',
      kind: 'sign',
      label: 'Read the sky over the lake',
      sprite: 'none',
      x: 20,
      y: 25,
      visibleWhen: { type: 'not', condition: { type: 'puzzleSolved', puzzle: 'p-sky' } },
      interaction: {
        verb: 'use',
        requires: { type: 'clueFound', clue: 'clue-hanina-east' },
        blockedText: 'Ask Old Hanina what the sky is saying first. He’s sitting right here.',
        effects: [{ type: 'openPuzzle', puzzle: 'p-sky' }],
      },
    },
    look(
      'western-hills',
      'Look west, over the hills',
      'clue-clear-west',
      'Over the hills to the west, behind the town, the sky is clear and golden. No rain clouds are coming in from the sea.',
      1,
      10,
      'none',
    ),
    look(
      'far-shore',
      'Look across to the far shore',
      'clue-cold-breath',
      'Across the lake the eastern hills are already in shadow. Now and then a cold breath comes over the water from them, against the afternoon wind, and the lake under them darkens and shivers.',
      41,
      16,
      'none',
    ),
    {
      ...look(
        'magdala-boat',
        'A boat just in from Magdala',
        'clue-magdala-crew',
        'The crew of this boat, just in from Magdala, have dragged it high up the shingle and are lashing it down. “We don’t like the feel of tonight,” one of them says.',
        9,
        14,
        'none',
      ),
      visibleWhen: DAY,
    },
    look(
      'waters-edge',
      'The water’s edge',
      'clue-afternoon-wind',
      'The afternoon wind from the west chops the lake into short waves that slap and hiss on the shingle.',
      16,
      17,
      'none',
    ),
    // ── Nikanor's salting place ─────────────────────────────────────────
    {
      id: 'nikanor',
      kind: 'npc',
      label: 'Nikanor the salt-fish trader',
      characterId: 'nikanor',
      x: 35,
      y: 9,
      facing: 'down',
      visibleWhen: DAY,
      interaction: { verb: 'talk', dialogue: 'd-nikanor' },
    },
    {
      id: 'brine-jars',
      kind: 'feature',
      label: 'Nikanor’s measuring jars',
      sprite: 'vessels',
      x: 37,
      y: 8,
      visibleWhen: DAY,
      interaction: {
        verb: 'use',
        requires: { type: 'questStage', quest: 'q-brine', stage: 'measure' },
        blockedText:
          'A big jar and a small jar beside the brine tubs, each marked with how much it holds — and nothing in between.',
        effects: [{ type: 'openPuzzle', puzzle: 'p-brine' }],
      },
    },
    {
      id: 'fish-rack',
      kind: 'feature',
      label: 'A basket of today’s catch',
      sprite: 'none',
      x: 28,
      y: 9,
      interaction: {
        verb: 'examine',
        effects: [
          {
            type: 'showMessage',
            text: 'Split fish drying in rows, and a basket of today’s catch: silver musht, a few barbels, and one whiskery catfish set aside. It has no scales, so no one here will eat it.',
          },
          { type: 'setFlag', flag: 'saw-catch', value: true },
        ],
      },
    },
    // ── The crowd and the teacher's boat (Mark 4:1) ──────────────────────
    {
      id: 'teacher-boat',
      kind: 'sign',
      label: 'A boat a little way offshore',
      sprite: 'none',
      x: 36,
      y: 17,
      visibleWhen: DAY,
      interaction: { verb: 'examine', dialogue: 'd-teacher-boat' },
    },
    {
      id: 'dinah',
      kind: 'npc',
      label: 'Dinah, in the crowd',
      characterId: 'dinah',
      x: 32,
      y: 14,
      facing: 'down',
      pose: 'sit',
      visibleWhen: DAY,
      interaction: { verb: 'talk', dialogue: 'd-dinah' },
    },
    {
      id: 'listener-1',
      kind: 'npc',
      label: 'Someone in the crowd',
      characterId: 'listener-a',
      x: 33,
      y: 13,
      facing: 'down',
      pose: 'sit',
      visibleWhen: DAY,
    },
    {
      id: 'listener-2',
      kind: 'npc',
      label: 'Someone in the crowd',
      characterId: 'listener-b',
      x: 35,
      y: 13,
      facing: 'down',
      pose: 'sit',
      visibleWhen: DAY,
    },
    {
      id: 'listener-3',
      kind: 'npc',
      label: 'Someone in the crowd',
      characterId: 'listener-c',
      x: 34,
      y: 15,
      facing: 'down',
      pose: 'sit',
      visibleWhen: DAY,
    },
    // ── Shifra's family ─────────────────────────────────────────────────
    {
      id: 'shifra',
      kind: 'npc',
      label: 'Shifra',
      characterId: 'shifra',
      x: 37,
      y: 14,
      facing: 'left',
      interaction: { verb: 'talk', dialogue: 'd-shifra' },
    },
    {
      id: 'ami',
      kind: 'npc',
      label: 'Ami',
      characterId: 'ami',
      x: 38,
      y: 14,
      facing: 'down',
      // Home in the night, wrapped in the cloak you gave him.
      looks: [
        {
          when: { type: 'choiceMade', choice: 'choice-cloak', option: 'given' },
          marks: ['wrapped-in-cloak'],
        },
        { when: NIGHT, pose: 'sit' },
      ],
      interaction: { verb: 'talk', dialogue: 'd-ami' },
    },
    {
      id: 'oded',
      kind: 'npc',
      label: 'Oded',
      characterId: 'oded',
      x: 41,
      y: 15,
      facing: 'left',
      interaction: { verb: 'talk', dialogue: 'd-oded' },
    },
    // ── What came home with you (night) ─────────────────────────────────
    {
      id: 'shelomit-night',
      kind: 'npc',
      label: 'Grandmother Shelomit, with a lamp',
      characterId: 'shelomit',
      x: 20,
      y: 17,
      facing: 'down',
      visibleWhen: NIGHT,
      interaction: { verb: 'talk', dialogue: 'd-shelomit-night' },
    },
    {
      id: 'grandmother-lamp',
      kind: 'feature',
      label: 'Grandmother’s lamp',
      sprite: 'lamp',
      x: 21,
      y: 17,
      solid: false,
      visibleWhen: NIGHT,
    },
    {
      id: 'nikanor-night',
      kind: 'npc',
      label: 'Nikanor, waiting',
      characterId: 'nikanor',
      x: 23,
      y: 12,
      facing: 'down',
      visibleWhen: NIGHT,
      interaction: { verb: 'talk', dialogue: 'd-nikanor' },
    },
    {
      id: 'jars-ashore',
      kind: 'feature',
      label: 'The jars you left on the shore',
      sprite: 'fish-jars',
      x: 27,
      y: 12,
      visibleWhen: all(NIGHT, flag('left-jars')),
    },
    {
      id: 'towline',
      kind: 'feature',
      label: 'The rope that towed their boat home',
      sprite: 'towline',
      x: 40,
      y: 16,
      solid: false,
      visibleWhen: all(NIGHT, storm('tow')),
    },
    {
      id: 'spare-oar-returned',
      kind: 'feature',
      label: 'Your spare oar, in their boat',
      sprite: 'oar',
      x: 37,
      y: 16,
      solid: false,
      visibleWhen: all(NIGHT, storm('oar')),
    },
  ],
  exits: [
    {
      id: 'to-house',
      label: 'Grandmother’s house',
      x: 6,
      y: 2,
      w: 1,
      h: 1,
      to: { scene: 'shelomit-house', spawn: 'from-shore' },
    },
  ],
  triggers: [
    {
      id: 'shore-intro',
      area: { x: 5, y: 3, w: 3, h: 2 },
      onceFlag: 'shore-intro',
      effects: [
        {
          type: 'showMessage',
          text: 'The shore is busy: nets drying, salters at their racks — and a great crowd along the beach, listening to someone speaking from a boat just offshore.',
        },
      ],
    },
    // Jars left on the jetty go back up to the rack (shown there when you come home).
    {
      id: 'jars-ashore',
      onceFlag: 'jars-counted',
      when: all(
        { type: 'puzzleSolved', puzzle: 'p-load' },
        not({ type: 'hasItem', item: 'fish-jar', min: 6 }),
        DAY,
      ),
      effects: [{ type: 'setFlag', flag: 'left-jars', value: true }],
    },
    // Once the boat is loaded, evening comes and the boats put out.
    {
      id: 'evening',
      onceFlag: 'evening-came',
      when: { type: 'puzzleSolved', puzzle: 'p-load' },
      effects: [
        { type: 'setFlag', flag: 'evening', value: true },
        { type: 'setCounter', counter: 'hour', value: 18 },
        { type: 'startDialogue', dialogue: 'd-evening' },
      ],
    },
    // Home in the night.
    {
      id: 'homecoming',
      onceFlag: 'home-greeted',
      when: NIGHT,
      effects: [{ type: 'startDialogue', dialogue: 'd-homecoming' }],
    },
  ],
  ambience: 'oasis',
  mood: 'oasis',
  music: 'home',
  // The westerly that blows most summer afternoons; it has dropped by evening.
  weather: 'wind',
  weatherChanges: [{ when: flag('evening'), weather: 'clear' }],
};
