import type { ChapterInput } from '@/domain/chapter';

/**
 * Everyone you meet in this chapter is FICTIONAL, with ordinary names of the
 * period. The people of Luke 2 — Mary, Joseph, the baby, the shepherds and
 * the angels — never appear on screen and never speak: the player hears of
 * them only through Scripture references, labelled paraphrase and what a
 * fictional neighbor reports. No biblical figure is ever player-controlled.
 */
export const CHARACTERS: ChapterInput['characters'] = [
  {
    id: 'tamar',
    name: 'Tamar',
    role: 'Your mother',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-tamar',
    appearance: {
      skin: '#a0704a',
      hair: '#2a1a10',
      robe: '#7a3f34',
      accent: '#e3c27a',
      headwear: 'veil',
      headwearColor: '#e8dcc0',
      beard: false,
      build: 'adult',
      carry: 'bread',
    },
  },
  {
    id: 'amram',
    name: 'Saba Amram',
    role: 'Your grandfather',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-amram',
    appearance: {
      skin: '#9a6a45',
      hair: '#dcd4c4',
      robe: '#5f5a44',
      accent: '#c9a45a',
      headwear: 'wrap',
      headwearColor: '#efe6d2',
      beard: true,
      build: 'elder',
      carry: 'staff',
    },
  },
  {
    id: 'asa',
    name: 'Uncle Asa',
    role: 'A stonemason, your mother’s brother',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-asa',
    appearance: {
      skin: '#946040',
      hair: '#2a1a10',
      robe: '#8a7a5c',
      accent: '#4f6a7a',
      headwear: 'band',
      headwearColor: '#6f4a2c',
      beard: true,
      build: 'adult',
      carry: 'bundle',
    },
  },
  {
    id: 'peninah',
    name: 'Aunt Peninah',
    role: 'Uncle Asa’s wife',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-peninah',
    appearance: {
      skin: '#b07a50',
      hair: '#1f1511',
      robe: '#35527a',
      accent: '#e8d49a',
      headwear: 'scarf',
      headwearColor: '#c96f3b',
      beard: false,
      build: 'adult',
    },
  },
  {
    id: 'dodi',
    name: 'Dodi',
    role: 'Your little cousin',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-dodi',
    appearance: {
      skin: '#b07a50',
      hair: '#1f1511',
      robe: '#d8c49a',
      accent: '#35527a',
      headwear: 'none',
      headwearColor: '#d8c49a',
      beard: false,
      build: 'child',
    },
  },
  {
    id: 'kallias',
    name: 'Kallias',
    role: 'Registration clerk',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-kallias',
    appearance: {
      skin: '#c08a5e',
      hair: '#3a2a1c',
      robe: '#e6dcc6',
      accent: '#3f5f8f',
      headwear: 'none',
      headwearColor: '#e6dcc6',
      beard: false,
      build: 'adult',
      carry: 'tablet',
    },
  },
  {
    id: 'hagit',
    name: 'Hagit',
    role: 'Your neighbor, who keeps goats',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-hagit',
    appearance: {
      skin: '#8a5a38',
      hair: '#cfc8bb',
      robe: '#556b3a',
      accent: '#d9b25f',
      headwear: 'veil',
      headwearColor: '#6b5a7a',
      beard: false,
      build: 'elder',
      carry: 'lamp',
    },
  },
  {
    id: 'yonatan',
    name: 'Cousin Yonatan',
    role: 'A young shepherd, your cousin',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-yonatan',
    appearance: {
      skin: '#8d5a3a',
      hair: '#1f1611',
      robe: '#8b7a5a',
      accent: '#a8322a',
      headwear: 'scarf',
      headwearColor: '#d8c49a',
      beard: false,
      build: 'adult',
      carry: 'staff',
    },
  },
  {
    id: 'yoram',
    name: 'Old Yoram',
    role: 'Shepherd of the village flock',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-yoram',
    appearance: {
      skin: '#7a4a2e',
      hair: '#e2dbcf',
      robe: '#6f5a3a',
      accent: '#5a4a3a',
      headwear: 'hood',
      headwearColor: '#8a6a4a',
      beard: true,
      build: 'elder',
      carry: 'lamb',
    },
  },
  {
    id: 'zerah',
    name: 'Zerah',
    role: 'A basket-maker from Tekoa',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-zerah',
    appearance: {
      skin: '#946040',
      hair: '#cfc8bb',
      robe: '#7a6448',
      accent: '#2f5590',
      headwear: 'wrap',
      headwearColor: '#c9b48a',
      beard: true,
      build: 'elder',
      carry: 'lamp',
    },
  },
];
