import type { ChapterInput } from '@/domain/chapter';
import type { Condition } from '@/domain/conditions';

const traveler = (option: string): Condition => ({
  type: 'choiceMade',
  choice: 'choice-traveler',
  option,
});

/** The edge of Jericho: a fictional wayside inn, the spring, and Rivka's courtyard. */
export const JERICHO: ChapterInput['scenes'][number] = {
  id: 'jericho',
  name: 'Jericho, the city of palm trees',
  kind: 'outdoor',
  description:
    'The road levels out among palm trees near a wayside inn. Further east lie a spring and Rivka’s courtyard.',
  layout: [
    '..............P,,,,,,,,,,,,,,,,,,,',
    '...^^^^^^^^^..r,,P,,,,,,,,,,,,,,,,',
    '...^^^^^^^^^..P,,,,,,,P,,,,,,,P,,,',
    '...^^^^^^^^^..r,,,~~~~,,,,,,,,,,,,',
    '...^^^^^^^^^..P,,,~~~~,,,,P,,,,,,,',
    '...####D####..r,,,~~~~,,,,,,,,,,,,',
    '..l==========.P,,,,,,,,,,,,,,,,,,,',
    '..l==========.r,P,,,,,,,,,,,,,,,,,',
    '..l=W========.P,,,,,,,,,,,,,,,,,P,',
    '..l==========.r,,,,,,,,,,,,,,P,,,,',
    '=========================,,=,,,,,,',
    '=============.r,,,,,,,,,,,,=,,,,,,',
    '..lllllllllll.P,,,,,,,,####g#####,',
    '..............r,P,,,,,,#====^^^^#,',
    '..............P,,,,,P,,#====^^^^#,',
    '..............r,,,,,,,,#======o=#,',
    '..............P,,,,,,,,#========#,',
    '..............r,,,,,,,,#========#,',
    '..............P,,,P,,,,#========#,',
    '..............r,,,,,,,,#j======j#,',
    '..............P,,,,,,,,##########,',
    '..............r,,,,,,,,,,,,,,,,,,,',
  ],
  legend: {
    ',': 'scrub',
    '.': 'sand',
    '=': 'paving',
    '^': 'roof',
    '#': 'wall',
    D: 'door',
    W: 'well',
    l: 'fence',
    P: 'palm',
    r: 'rock',
    '~': 'water',
    g: 'gate',
    o: 'oven',
    j: 'jars',
  },
  baseTile: 'scrub',
  spawns: { 'from-road': { x: 1, y: 10, facing: 'right' } },
  entities: [
    {
      id: 'salome',
      kind: 'npc',
      label: 'Salome the innkeeper',
      characterId: 'salome',
      x: 8,
      y: 7,
      facing: 'down',
      interaction: { verb: 'talk', dialogue: 'd-salome' },
    },
    {
      id: 'menashe-inn',
      kind: 'npc',
      label: 'Menashe',
      characterId: 'menashe',
      x: 5,
      y: 7,
      facing: 'right',
      visibleWhen: { type: 'any', of: [traveler('tend-walk'), traveler('tend-caravan')] },
      interaction: { verb: 'talk', dialogue: 'd-menashe-inn' },
    },
    {
      id: 'bedroll',
      kind: 'feature',
      label: 'Sleeping mat',
      sprite: 'bedroll',
      x: 4,
      y: 7,
      solid: false,
      visibleWhen: { type: 'any', of: [traveler('tend-walk'), traveler('tend-caravan')] },
    },
    {
      id: 'malik-inn',
      kind: 'npc',
      label: 'Malik',
      characterId: 'malik',
      x: 10,
      y: 8,
      facing: 'left',
      visibleWhen: traveler('tend-caravan'),
      interaction: { verb: 'talk', dialogue: 'd-malik-inn' },
    },
    { id: 'inn-donkey', kind: 'feature', label: 'The inn’s donkey', sprite: 'donkey', x: 11, y: 7 },
    {
      id: 'night',
      kind: 'feature',
      label: 'The dark road to Jericho',
      sprite: 'lamp',
      x: 14,
      y: 10,
      visibleWhen: {
        type: 'all',
        of: [
          { type: 'counter', counter: 'hour', gte: 18 },
          { type: 'not', condition: { type: 'hasItem', item: 'lamp' } },
          { type: 'not', condition: { type: 'flag', flag: 'stayed-night' } },
        ],
      },
      interaction: { verb: 'examine', dialogue: 'd-night' },
    },
    {
      id: 'spring',
      kind: 'sign',
      label: 'The spring',
      sprite: 'sign',
      x: 17,
      y: 4,
      interaction: {
        verb: 'examine',
        effects: [
          {
            type: 'showMessage',
            text: 'A strong spring feeds a clear pool here. Palms, gardens and orchards spread out around it.',
          },
        ],
      },
    },
    {
      id: 'rivka',
      kind: 'npc',
      label: 'Rivka',
      characterId: 'rivka',
      x: 27,
      y: 16,
      facing: 'up',
      interaction: { verb: 'talk', dialogue: 'd-rivka' },
    },
    {
      id: 'natan',
      kind: 'npc',
      label: 'Natan',
      characterId: 'natan',
      x: 29,
      y: 17,
      facing: 'left',
      interaction: { verb: 'talk', dialogue: 'd-natan' },
    },
    { id: 'natan-mat', kind: 'feature', label: 'Natan’s mat', sprite: 'bedroll', x: 30, y: 17 },
    {
      id: 'yair',
      kind: 'npc',
      label: 'Yair',
      characterId: 'yair',
      x: 25,
      y: 16,
      facing: 'right',
      interaction: { verb: 'talk', dialogue: 'd-yair' },
    },
  ],
  exits: [],
  triggers: [
    {
      id: 'inn-arrival',
      area: { x: 1, y: 9, w: 2, h: 3 },
      onceFlag: 'inn-arrival',
      effects: [{ type: 'startDialogue', dialogue: 'd-inn-arrival' }],
    },
  ],
  ambience: 'oasis',
  music: 'home',
};
