import type { ChapterInput } from '@/domain/chapter';

/** The lower market, Jerusalem — a fictional composite near the east gate. */
export const JERUSALEM_MARKET: ChapterInput['scenes'][number] = {
  id: 'jerusalem-market',
  name: 'The lower market, Jerusalem',
  kind: 'outdoor',
  description:
    'A busy market square around a well. Stalls, a bakery and a caravan camp crowd toward the east gate, where the road leads down to Jericho.',
  layout: [
    '##################################',
    '#.^^^^^^^......SSS..^^^^^^^^.....#',
    '#.^^^^^^^...........^^^^^^^^.....#',
    '#.^^^^^^^...........^^^^^^^^.....#',
    '#.###D###...........########.....#',
    '#j...=.............b............k#',
    '#....=....=sssbjk==sso===.T......#',
    '#.T..====================....T...#',
    '#,,,,,,,,.===============..tt....#',
    '#,,,,,,,,.===============......r.#',
    '#,,,,CC,,.===============........#',
    '#,,T,,,,,.=======W===============g',
    '#,,,,,,,,.=======================g',
    '#,,,,,,,,.===============........#',
    '#,T,,,,,,.===============......j.#',
    '#,CC,,,,,.===============.j......#',
    '#,,,,,T,,.=ss=kb==ss=cc==.j......#',
    '#,,,,,,,,b.................hk...T#',
    '#c.........T..........T...llllll.#',
    '#^^^^^^^^^.....................r.#',
    '#^^^^^^^^^.............^^^^^^^^^^#',
    '#^^^^^^^^^.............^^^^^^^^^^#',
    '#^^^^^^^^^.............^^^^^^^^^^#',
    '##################################',
  ],
  legend: {
    '#': 'wall',
    '^': 'roof',
    D: 'door',
    '.': 'sand',
    ',': 'scrub',
    '=': 'paving',
    s: 'stall',
    o: 'oven',
    W: 'well',
    T: 'olive',
    r: 'rock',
    j: 'jars',
    l: 'fence',
    g: 'gate',
    S: 'steps',
    k: 'sacks',
    b: 'basket',
    c: 'crate',
    t: 'tent',
    h: 'trough',
    C: 'cloth',
  },
  baseTile: 'sand',
  spawns: { 'from-house': { x: 5, y: 5, facing: 'down' } },
  entities: [
    {
      id: 'hadassah',
      kind: 'npc',
      label: 'Hadassah the weaver',
      characterId: 'hadassah',
      x: 12,
      y: 7,
      facing: 'down',
      interaction: { verb: 'talk', dialogue: 'd-hadassah' },
    },
    {
      id: 'ezer',
      kind: 'npc',
      label: 'Ezer the baker',
      characterId: 'ezer',
      x: 20,
      y: 7,
      facing: 'down',
      interaction: { verb: 'talk', dialogue: 'd-ezer' },
    },
    {
      id: 'menashe',
      kind: 'npc',
      label: 'Menashe the oil merchant',
      characterId: 'menashe',
      x: 17,
      y: 8,
      facing: 'right',
      interaction: { verb: 'talk', dialogue: 'd-menashe' },
    },
    {
      id: 'vessels',
      kind: 'feature',
      label: 'Ezer’s measuring vessels',
      sprite: 'vessels',
      x: 22,
      y: 7,
      interaction: {
        verb: 'use',
        requires: { type: 'questStage', quest: 'q-honest-measure', stage: 'measure' },
        blockedText:
          'A big crock and a pitcher, both marked with how much they hold. They might help settle an argument.',
        effects: [{ type: 'openPuzzle', puzzle: 'p-measure' }],
      },
    },
    {
      id: 'hanan',
      kind: 'npc',
      label: 'Hanan the Levite',
      characterId: 'hanan',
      x: 18,
      y: 2,
      facing: 'left',
      interaction: { verb: 'talk', dialogue: 'd-hanan' },
    },
    {
      id: 'steps-sign',
      kind: 'sign',
      label: 'Steps up toward the Temple',
      sprite: 'sign',
      x: 14,
      y: 1,
      interaction: {
        verb: 'read',
        effects: [
          {
            type: 'showMessage',
            text: 'These steps climb toward the Temple courts. Not today — your road leads east, down to Jericho.',
          },
        ],
      },
    },
    {
      id: 'well',
      kind: 'feature',
      label: 'The market well',
      x: 17,
      y: 11,
      sprite: 'none',
      solid: true,
      interaction: {
        verb: 'examine',
        effects: [
          {
            type: 'showMessage',
            text: 'Cool water, and a crowd of people talking. A good place to hear news.',
          },
        ],
      },
    },
    {
      id: 'malik',
      kind: 'npc',
      label: 'Malik the trader',
      characterId: 'malik',
      x: 27,
      y: 14,
      facing: 'left',
      interaction: { verb: 'talk', dialogue: 'd-malik' },
    },
    { id: 'donkey-1', kind: 'feature', label: 'Caravan donkey', sprite: 'donkey', x: 29, y: 15 },
    { id: 'donkey-2', kind: 'feature', label: 'Caravan donkey', sprite: 'donkey', x: 30, y: 17 },
    { id: 'bales', kind: 'feature', label: 'Trade goods', sprite: 'basket', x: 28, y: 16 },
    {
      id: 'shimon',
      kind: 'npc',
      label: 'Old Shimon',
      characterId: 'shimon',
      x: 30,
      y: 9,
      facing: 'down',
      interaction: { verb: 'talk', dialogue: 'd-shimon' },
    },
    {
      id: 'tobiah',
      kind: 'npc',
      label: 'Tobiah the carter',
      characterId: 'tobiah',
      x: 26,
      y: 13,
      facing: 'up',
      interaction: { verb: 'talk', dialogue: 'd-tobiah' },
    },
    { id: 'cart', kind: 'feature', label: 'Tobiah’s cart', sprite: 'basket', x: 25, y: 13 },
    {
      id: 'gate-sign',
      kind: 'sign',
      label: 'Sign by the east gate',
      sprite: 'sign',
      x: 31,
      y: 10,
      interaction: {
        verb: 'read',
        effects: [
          {
            type: 'showMessage',
            text: 'East gate. The road beyond runs down through the wilderness to Jericho.',
          },
        ],
      },
    },
  ],
  exits: [
    {
      id: 'to-house',
      label: 'Aunt Miriam’s house',
      x: 5,
      y: 4,
      w: 1,
      h: 1,
      to: { scene: 'miriam-house', spawn: 'from-market' },
    },
    {
      id: 'east-gate',
      label: 'the east gate (road to Jericho)',
      x: 33,
      y: 11,
      w: 1,
      h: 2,
      to: { scene: 'jericho-road', spawn: 'from-jerusalem' },
      requires: { type: 'puzzleSolved', puzzle: 'p-satchel' },
      blockedDialogue: 'd-gate-blocked',
      effects: [{ type: 'adjustCounter', counter: 'hour', delta: 1 }],
    },
  ],
  triggers: [
    {
      id: 'market-intro',
      area: { x: 4, y: 5, w: 3, h: 3 },
      onceFlag: 'market-intro',
      effects: [
        {
          type: 'showMessage',
          text: 'The market is busy. Travelers here may know about the road — try talking to people.',
        },
      ],
    },
  ],
  ambience: 'market',
  mood: 'city',
  music: 'home',
};
