import type { ChapterInput } from '@/domain/chapter';

const flag = (name: string) => ({ type: 'flag' as const, flag: name });

/**
 * A street in Colossae — a fictional composite. Colossae's buried city has
 * never been dug (the first excavations, from 2025, were in its cemetery), so
 * this street is modelled on Roman-era towns of the region: a colonnade with
 * shops, tiled roofs, a public fountain, workshops for the wool trade.
 */
export const COLOSSAE_STREET: ChapterInput['scenes'][number] = {
  id: 'colossae-street',
  name: 'A street in Colossae',
  kind: 'outdoor',
  description:
    'A paved street under a colonnade of shops, with a fountain in a little square. Tatia’s fullery steams on the south side, and Mount Cadmus rises behind the roofs.',
  layout: [
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    '####D######D####D###D#########gg######',
    '#============t=======s======b====b===#',
    '#=========|==|==|==|==|==============#',
    '#======jjs===========================#',
    '#==================================f=#',
    'G====================================#',
    'G=================F==================#',
    '#====================================#',
    '#====================================#',
    '#==f=================================#',
    '#===================llllll==llllll===#',
    '#===================l,,,,,,,,CCC,l,,,#',
    '#===================l,v,v,,,,,,,,l,,,#',
    '#===================l,,,,,,,,,,,al,,,#',
    '#,r,,,b,,b,,r,,,r,,,l,v,v,,,,,,,al,,,#',
    '#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH#',
    '#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH#',
    '#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH#',
    'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
  ],
  legend: {
    T: 'tile-roof',
    '#': 'wall',
    D: 'door',
    g: 'gate',
    G: 'gate',
    '=': 'paving',
    '|': 'column',
    t: 'table',
    s: 'stall',
    b: 'bush',
    j: 'jars',
    F: 'fountain',
    f: 'fig',
    l: 'fence',
    ',': 'scrub',
    v: 'vat',
    C: 'cloth',
    a: 'amphorae',
    r: 'rock',
    H: 'hill',
  },
  baseTile: 'paving',
  spawns: {
    'from-workshop': { x: 4, y: 4, facing: 'down' },
    'from-road': { x: 1, y: 9, facing: 'right' },
    'from-philemon': { x: 30, y: 4, facing: 'down' },
  },
  entities: [
    {
      id: 'zenon',
      kind: 'npc',
      label: 'Zenon the scribe',
      characterId: 'zenon',
      x: 14,
      y: 4,
      facing: 'down',
      visibleWhen: { type: 'not', condition: flag('back-in-town') },
      interaction: { verb: 'talk', dialogue: 'd-zenon' },
    },
    {
      id: 'zenon-table',
      kind: 'feature',
      label: 'Zenon’s writing table',
      sprite: 'letter-sheets',
      x: 13,
      y: 4,
      visibleWhen: { type: 'not', condition: { type: 'puzzleSolved', puzzle: 'p-sheets' } },
      interaction: {
        verb: 'use',
        requires: { type: 'hasItem', item: 'kallias-letter' },
        blockedText: 'Zenon’s table: pens, a pot of ink, a knife for trimming papyrus.',
        effects: [{ type: 'openPuzzle', puzzle: 'p-sheets' }],
      },
    },
    {
      id: 'menandros',
      kind: 'npc',
      label: 'Menandros the potter',
      characterId: 'menandros',
      x: 10,
      y: 6,
      facing: 'down',
      interaction: { verb: 'talk', dialogue: 'd-menandros' },
    },
    {
      id: 'attalos',
      kind: 'npc',
      label: 'Attalos the mule driver',
      characterId: 'attalos',
      x: 20,
      y: 9,
      facing: 'left',
      // He leaves for Laodicea once you have gone down the road yourself.
      visibleWhen: { type: 'not', condition: { type: 'visited', scene: 'lycus-road' } },
      interaction: { verb: 'talk', dialogue: 'd-attalos' },
    },
    {
      id: 'mule',
      kind: 'feature',
      label: 'Attalos’s mule',
      sprite: 'pack-donkey',
      x: 21,
      y: 10,
      visibleWhen: { type: 'not', condition: { type: 'visited', scene: 'lycus-road' } },
    },
    {
      id: 'fountain',
      kind: 'feature',
      label: 'The fountain',
      sprite: 'none',
      x: 18,
      y: 9,
      solid: true,
      interaction: {
        verb: 'examine',
        effects: [
          {
            type: 'showMessage',
            text: 'Cold water runs from a spout into a stone basin. Women fill jars here, and everyone passing stops to hear the news.',
          },
        ],
      },
    },
    {
      id: 'tatia',
      kind: 'npc',
      label: 'Tatia the fuller',
      characterId: 'tatia',
      x: 27,
      y: 15,
      facing: 'up',
      visibleWhen: { type: 'not', condition: flag('back-in-town') },
      interaction: { verb: 'talk', dialogue: 'd-tatia' },
    },
    {
      id: 'fullers-clay',
      kind: 'feature',
      label: 'Tatia’s yard',
      sprite: 'none',
      x: 26,
      y: 13,
      solid: false,
      interaction: {
        verb: 'examine',
        effects: [
          { type: 'setFlag', flag: 'saw-fullers-clay', value: true },
          {
            type: 'showMessage',
            text: 'Everything in Tatia’s yard wears a coat of fine white clay dust — the vats, the posts, the cloth waiting to be rinsed.',
          },
        ],
      },
    },
    {
      id: 'cadmus',
      kind: 'feature',
      label: 'Mount Cadmus',
      sprite: 'none',
      x: 14,
      y: 18,
      solid: true,
      interaction: {
        verb: 'examine',
        effects: [
          { type: 'discoverClue', clue: 'clue-rain-coming' },
          {
            type: 'showMessage',
            text: 'Behind the town, Mount Cadmus climbs into grey cloud. The cloud is thickening, and it is moving down the valley.',
          },
        ],
      },
    },
    {
      id: 'stoa',
      kind: 'sign',
      label: 'The colonnade',
      sprite: 'none',
      x: 16,
      y: 5,
      solid: true,
      interaction: {
        verb: 'examine',
        effects: [
          { type: 'setFlag', flag: 'saw-colonnade', value: true },
          {
            type: 'showMessage',
            text: 'A roofed walk behind a row of stone columns, with shops opening off the back of it. In the shade you can work, talk — or have a letter written.',
          },
        ],
      },
    },
    {
      id: 'philemon-gate',
      kind: 'sign',
      label: 'The gate of Philemon’s house',
      sprite: 'none',
      x: 29,
      y: 4,
      solid: false,
      interaction: {
        verb: 'examine',
        effects: [
          {
            type: 'showMessage',
            text: 'The gate of Philemon’s house. The travellers from Paul are staying inside. Tonight, at lamp-lighting, the assembly gathers here.',
          },
        ],
      },
    },
  ],
  exits: [
    {
      id: 'to-workshop',
      label: 'Ammia’s workshop',
      x: 4,
      y: 3,
      w: 1,
      h: 1,
      to: { scene: 'ammia-workshop', spawn: 'from-street' },
    },
    {
      id: 'west-gate',
      label: 'the west gate (the road to Laodicea)',
      x: 0,
      y: 8,
      w: 1,
      h: 2,
      to: { scene: 'lycus-road', spawn: 'from-colossae' },
      requires: { type: 'puzzleSolved', puzzle: 'p-pack' },
      blockedDialogue: 'd-gate-blocked',
      effects: [{ type: 'adjustCounter', counter: 'hour', delta: 1 }],
    },
    {
      id: 'to-philemon',
      label: 'Philemon’s house',
      x: 30,
      y: 3,
      w: 2,
      h: 1,
      to: { scene: 'philemon-house', spawn: 'from-street' },
      requires: flag('back-in-town'),
      blockedText:
        'The gate of Philemon’s house is shut. The gathering is this evening, at lamp-lighting.',
      effects: [{ type: 'setCounter', counter: 'hour', value: 18 }],
    },
  ],
  triggers: [
    {
      id: 'street-intro',
      area: { x: 3, y: 4, w: 3, h: 3 },
      onceFlag: 'street-intro',
      effects: [
        {
          type: 'showMessage',
          text: 'Zenon the scribe works under the colonnade. Everyone in the street seems to be talking about the travellers at Philemon’s house.',
        },
      ],
    },
    // Coming home from the road, once you've decided what to do at the dye works.
    {
      id: 'back-in-town',
      onceFlag: 'back-in-town',
      when: { type: 'choiceMade', choice: 'choice-kallias' },
      effects: [{ type: 'startDialogue', dialogue: 'd-back-in-town' }],
    },
  ],
  ambience: 'market',
  mood: 'city',
  music: 'home',
  weatherChanges: [
    { when: flag('rain-began'), weather: 'rain' },
    { when: flag('back-in-town'), weather: 'clear' },
  ],
};
