import type { ChapterInput } from '@/domain/chapter';

/**
 * Everyone you meet in this chapter is FICTIONAL. Names are ordinary names
 * of the period. Jesus does not appear as a character: the chapter only
 * reports that people heard a story he told (Luke 10:25–37).
 */
export const CHARACTERS: ChapterInput['characters'] = [
  {
    id: 'miriam',
    name: 'Aunt Miriam',
    role: 'Healer, your aunt',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-miriam',
    appearance: {
      skin: '#9a6a45',
      hair: '#4a3a30',
      robe: '#7a4b3a',
      accent: '#e3c27a',
      headwear: 'veil',
      headwearColor: '#efe3c8',
      beard: false,
      build: 'adult',
      carry: 'basket',
    },
  },
  {
    id: 'malik',
    name: 'Malik',
    role: 'Nabataean trader',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-malik',
    appearance: {
      skin: '#7a4a2e',
      hair: '#1c1410',
      robe: '#2f5f6f',
      accent: '#d9a441',
      headwear: 'wrap',
      headwearColor: '#c9b48a',
      beard: true,
      build: 'adult',
      carry: 'bundle',
    },
  },
  {
    id: 'shimon',
    name: 'Old Shimon',
    role: 'Shepherd from the wilderness',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-shimon',
    appearance: {
      skin: '#8a5a3a',
      hair: '#d8d0c0',
      robe: '#8b7a5a',
      accent: '#5a4a3a',
      headwear: 'scarf',
      headwearColor: '#e8dcc0',
      beard: true,
      build: 'elder',
      carry: 'staff',
    },
  },
  {
    id: 'tobiah',
    name: 'Tobiah',
    role: 'Carter',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-tobiah',
    appearance: {
      skin: '#a0704a',
      hair: '#2a1a10',
      robe: '#5f6f3a',
      accent: '#c9a45a',
      headwear: 'band',
      headwearColor: '#8a2f2f',
      beard: true,
      build: 'adult',
    },
  },
  {
    id: 'hadassah',
    name: 'Hadassah',
    role: 'Weaver',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-hadassah',
    appearance: {
      skin: '#b07a50',
      hair: '#2a1a12',
      robe: '#3f5f8f',
      accent: '#e8d49a',
      headwear: 'scarf',
      headwearColor: '#d9b25f',
      beard: false,
      build: 'adult',
      carry: 'spindle',
    },
  },
  {
    id: 'ezer',
    name: 'Ezer',
    role: 'Baker',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-ezer',
    appearance: {
      skin: '#9a6040',
      hair: '#2a1a10',
      robe: '#ddd0b2',
      accent: '#8a4f2f',
      headwear: 'wrap',
      headwearColor: '#f0e6d0',
      beard: true,
      build: 'adult',
      carry: 'bread',
    },
  },
  {
    id: 'menashe',
    name: 'Menashe',
    role: 'Samaritan oil merchant',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-menashe',
    appearance: {
      skin: '#8f5f3f',
      hair: '#1f1510',
      robe: '#6f5a3a',
      accent: '#3f6f8f',
      headwear: 'wrap',
      headwearColor: '#d8c8a0',
      beard: true,
      build: 'adult',
      carry: 'jar',
    },
  },
  {
    id: 'hanan',
    name: 'Hanan',
    role: 'A young Levite',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-hanan',
    appearance: {
      skin: '#a57550',
      hair: '#2a1a10',
      robe: '#efe6d2',
      accent: '#3f5f8f',
      headwear: 'none',
      headwearColor: '#efe6d2',
      beard: false,
      build: 'adult',
    },
  },
  {
    id: 'salome',
    name: 'Salome',
    role: 'Innkeeper',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-salome',
    appearance: {
      skin: '#8a5a38',
      hair: '#1a1210',
      robe: '#8f3f2f',
      accent: '#e2b555',
      headwear: 'veil',
      headwearColor: '#d8c8a8',
      beard: false,
      build: 'adult',
      carry: 'jar',
    },
  },
  {
    id: 'rivka',
    name: 'Rivka',
    role: 'Aunt Miriam’s friend in Jericho',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-rivka',
    appearance: {
      skin: '#9a6a45',
      hair: '#2a1a10',
      robe: '#556b3a',
      accent: '#e8d49a',
      headwear: 'veil',
      headwearColor: '#efe3c8',
      beard: false,
      build: 'adult',
    },
  },
  {
    id: 'natan',
    name: 'Natan',
    role: 'Rivka’s son',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-natan',
    appearance: {
      skin: '#9a6a45',
      hair: '#2a1a10',
      robe: '#c9a878',
      accent: '#556b3a',
      headwear: 'none',
      headwearColor: '#c9a878',
      beard: false,
      build: 'child',
    },
  },
  {
    id: 'yair',
    name: 'Yair',
    role: 'Rivka’s brother, a fig grower',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-yair',
    appearance: {
      skin: '#9a6040',
      hair: '#3a2a1c',
      robe: '#6b5236',
      accent: '#d9b25f',
      headwear: 'scarf',
      headwearColor: '#c9b48a',
      beard: true,
      build: 'adult',
      carry: 'basket',
    },
  },
];
