import type { ChapterInput } from '@/domain/chapter';

/**
 * Every item matters to a decision or a puzzle. Weights make the satchel a
 * real trade-off: capacity is 6 (see puzzles.ts).
 */
export const ITEMS: ChapterInput['items'] = [
  {
    id: 'remedy',
    name: 'Aunt Miriam’s remedy',
    kind: 'medicine',
    weight: 1,
    maxStack: 1,
    essential: true,
    icon: '🏺',
    description:
      'A sealed jar of herbs Aunt Miriam prepared for Rivka’s son, Natan, who has a fever. It must reach Jericho.',
  },
  {
    id: 'letter',
    name: 'Letter to Rivka',
    kind: 'letter',
    weight: 0,
    maxStack: 1,
    essential: true,
    icon: '✉️',
    description: 'Aunt Miriam’s note explaining how to prepare the remedy.',
  },
  {
    id: 'linen-bundle',
    name: 'Linen for Rivka',
    kind: 'supply',
    weight: 1,
    maxStack: 1,
    essential: true,
    icon: '🧺',
    description:
      'A bundle of fine linen sheets Hadassah the weaver made for Rivka: cool bedding for Natan, because down in Jericho it is too warm for wool. Already paid for.',
  },
  {
    id: 'coins',
    name: 'Bronze coins',
    kind: 'currency',
    weight: 0,
    maxStack: 20,
    essential: false,
    icon: '🪙',
    description: 'Small bronze coins for everyday buying.',
  },
  {
    id: 'water-skin',
    name: 'Water skin',
    kind: 'water',
    weight: 2,
    maxStack: 3,
    essential: false,
    icon: '💧',
    description: 'A goatskin full of water. Heavy — but the road is hot and dry.',
  },
  {
    id: 'bread',
    name: 'Bread and dates',
    kind: 'food',
    weight: 1,
    maxStack: 2,
    essential: false,
    icon: '🍞',
    description: 'Flat bread and a handful of dates, wrapped in cloth.',
  },
  {
    id: 'oil',
    name: 'Flask of olive oil',
    kind: 'supply',
    weight: 1,
    maxStack: 2,
    essential: false,
    icon: '🫒',
    description: 'Olive oil was used for cooking, for lamps — and to soothe wounds.',
  },
  {
    id: 'linen',
    name: 'Linen strips',
    kind: 'supply',
    weight: 1,
    maxStack: 1,
    essential: false,
    icon: '🧵',
    description: 'Clean strips of linen that could bind a wound.',
  },
  {
    id: 'lamp',
    name: 'Clay oil lamp',
    kind: 'tool',
    weight: 1,
    maxStack: 1,
    essential: false,
    icon: '🪔',
    description: 'A small clay lamp. Useful if you are still walking after dark.',
  },
  {
    id: 'cloak',
    name: 'Spare cloak',
    kind: 'clothing',
    weight: 2,
    maxStack: 1,
    essential: false,
    icon: '🧣',
    description: 'A warm wool cloak. Bulky to carry.',
  },
  {
    id: 'map',
    name: 'Malik’s sketch map',
    kind: 'map',
    weight: 0,
    maxStack: 1,
    essential: false,
    icon: '🗺️',
    description:
      'A trader’s scratched map of the road down to Jericho. It shows a shepherds’ path along the ridge that rejoins the road below the bend, and marks the wadi as ending at “the drop.”',
  },
];
