import type { Condition } from '@/domain/conditions';
import type { ChapterInput } from '@/domain/chapter';

const met = (character: string): Condition => ({ type: 'met', character });
const flag = (name: string): Condition => ({ type: 'flag', flag: name });

/**
 * The journal. Each entry is a list of labelled ContentRecords, so the
 * journal always shows whether a paragraph is Scripture, paraphrase,
 * history, reconstruction, interpretation or story.
 */
export const JOURNAL: ChapterInput['journal'] = [
  // People (unlocked on meeting via character.journalEntry)
  {
    id: 'jp-miriam',
    category: 'people',
    title: 'Aunt Miriam',
    summary: 'Healer, your aunt',
    recordIds: ['rec-p-miriam'],
    characterId: 'miriam',
    order: 1,
  },
  {
    id: 'jp-malik',
    category: 'people',
    title: 'Malik',
    summary: 'Nabataean trader',
    recordIds: ['rec-p-malik'],
    characterId: 'malik',
    order: 2,
  },
  {
    id: 'jp-shimon',
    category: 'people',
    title: 'Old Shimon',
    summary: 'Shepherd from the wilderness',
    recordIds: ['rec-p-shimon'],
    characterId: 'shimon',
    order: 3,
  },
  {
    id: 'jp-tobiah',
    category: 'people',
    title: 'Tobiah',
    summary: 'Carter',
    recordIds: ['rec-p-tobiah'],
    characterId: 'tobiah',
    order: 4,
  },
  {
    id: 'jp-hadassah',
    category: 'people',
    title: 'Hadassah',
    summary: 'Weaver',
    recordIds: ['rec-p-hadassah'],
    characterId: 'hadassah',
    order: 5,
  },
  {
    id: 'jp-ezer',
    category: 'people',
    title: 'Ezer',
    summary: 'Baker',
    recordIds: ['rec-p-ezer'],
    characterId: 'ezer',
    order: 6,
  },
  {
    id: 'jp-menashe',
    category: 'people',
    title: 'Menashe',
    summary: 'Samaritan oil merchant',
    recordIds: ['rec-p-menashe', 'rec-hist-samaritans'],
    characterId: 'menashe',
    order: 7,
  },
  {
    id: 'jp-hanan',
    category: 'people',
    title: 'Hanan',
    summary: 'A young Levite',
    recordIds: ['rec-p-hanan', 'rec-hist-priests-levites'],
    characterId: 'hanan',
    order: 8,
  },
  {
    id: 'jp-salome',
    category: 'people',
    title: 'Salome',
    summary: 'Innkeeper',
    recordIds: ['rec-p-salome', 'rec-pl-inn'],
    characterId: 'salome',
    order: 9,
  },
  {
    id: 'jp-rivka',
    category: 'people',
    title: 'Rivka',
    summary: 'Aunt Miriam’s friend in Jericho',
    recordIds: ['rec-p-rivka'],
    characterId: 'rivka',
    order: 10,
  },
  {
    id: 'jp-natan',
    category: 'people',
    title: 'Natan',
    summary: 'Rivka’s son',
    recordIds: ['rec-p-natan'],
    characterId: 'natan',
    order: 11,
  },
  {
    id: 'jp-yair',
    category: 'people',
    title: 'Yair',
    summary: 'Rivka’s brother',
    recordIds: ['rec-p-yair'],
    characterId: 'yair',
    order: 12,
  },

  // Places
  {
    id: 'jpl-market',
    category: 'places',
    title: 'The lower market, Jerusalem',
    summary: 'Where your journey begins',
    recordIds: ['rec-pl-market', 'rec-hist-descent'],
    unlockWhen: { type: 'visited', scene: 'jerusalem-market' },
    order: 1,
  },
  {
    id: 'jpl-road',
    category: 'places',
    title: 'The road down to Jericho',
    summary: 'A steep road through the wilderness',
    recordIds: ['rec-hist-descent', 'rec-hist-road-surface', 'rec-hist-road-danger'],
    unlockWhen: { type: 'visited', scene: 'jericho-road' },
    order: 2,
  },
  {
    id: 'jpl-adummim',
    category: 'places',
    title: 'The Ascent of Adummim',
    summary: 'The “red” climb named in Joshua',
    recordIds: ['rec-hist-adummim', 'rec-josh-15-7'],
    unlockWhen: flag('read-red-rocks'),
    order: 3,
  },
  {
    id: 'jpl-jericho',
    category: 'places',
    title: 'Jericho',
    summary: 'The city of palm trees',
    recordIds: ['rec-hist-jericho', 'rec-deut-34-3'],
    unlockWhen: { type: 'visited', scene: 'jericho' },
    order: 4,
  },
  {
    id: 'jpl-inn',
    category: 'places',
    title: 'The wayside inn',
    summary: 'Salome’s inn near Jericho',
    recordIds: ['rec-pl-inn', 'rec-hist-inn'],
    unlockWhen: met('salome'),
    order: 5,
  },

  // Events
  {
    id: 'je-mission',
    category: 'events',
    title: 'A remedy for Jericho',
    summary: 'Aunt Miriam’s request',
    recordIds: ['rec-e-mission'],
    order: 1,
  },
  {
    id: 'je-dispute',
    category: 'events',
    title: 'An argument in the market',
    summary: 'Ezer and Menashe',
    recordIds: ['rec-e-dispute'],
    order: 2,
  },
  {
    id: 'je-injured',
    category: 'events',
    title: 'Someone on the road',
    summary: 'Below the bend',
    recordIds: ['rec-e-injured'],
    unlockWhen: flag('incident-seen'),
    order: 3,
  },
  {
    id: 'je-arrival',
    category: 'events',
    title: 'Journey’s end',
    summary: 'Jericho at last',
    recordIds: ['rec-e-arrival'],
    order: 4,
  },
  {
    id: 'je-story',
    category: 'events',
    title: 'A story Jesus told',
    summary: 'Luke 10:25–37',
    recordIds: ['rec-para-luke-10', 'rec-luke-10-25-37'],
    unlockWhen: flag('heard-yair'),
    order: 5,
  },

  // History & culture
  {
    id: 'jh-samaritans',
    category: 'history',
    title: 'Jews and Samaritans',
    summary: 'Neighbors who kept their distance',
    recordIds: ['rec-hist-samaritans', 'rec-john-4-9', 'rec-luke-9-52-54'],
    unlockWhen: met('menashe'),
    order: 1,
  },
  {
    id: 'jh-priests',
    category: 'history',
    title: 'Priests and Levites',
    summary: 'Who served at the Temple',
    recordIds: ['rec-hist-priests-levites'],
    unlockWhen: met('hanan'),
    order: 2,
  },
  {
    id: 'jh-oil-wine',
    category: 'history',
    title: 'Oil and wine',
    summary: 'First aid in the ancient world',
    recordIds: ['rec-hist-oil-wine', 'rec-isa-1-6'],
    unlockWhen: { type: 'any', of: [{ type: 'hasItem', item: 'oil' }, flag('heard-yair')] },
    order: 3,
  },
  {
    id: 'jh-coins',
    category: 'history',
    title: 'Coins and wages',
    summary: 'What two denarii meant',
    recordIds: ['rec-hist-coins', 'rec-matt-20-2'],
    unlockWhen: flag('bought-something'),
    order: 4,
  },
  {
    id: 'jh-measures',
    category: 'history',
    title: 'Measuring oil',
    summary: 'The “log” of Leviticus 14',
    recordIds: ['rec-hist-measures'],
    order: 5,
  },
  {
    id: 'jh-floods',
    category: 'history',
    title: 'Flash floods',
    summary: 'Why dry wadis can be dangerous',
    recordIds: ['rec-hist-floods'],
    unlockWhen: {
      type: 'any',
      of: [
        { type: 'clueFound', clue: 'clue-mud-line' },
        { type: 'clueFound', clue: 'clue-clouds' },
      ],
    },
    order: 6,
  },
  {
    id: 'jh-inns',
    category: 'history',
    title: 'Inns on the road',
    summary: 'The pandocheion',
    recordIds: ['rec-hist-inn'],
    unlockWhen: met('salome'),
    order: 7,
  },

  // Scripture
  {
    id: 'js-luke-10',
    category: 'scripture',
    title: 'Luke 10:25–37',
    summary: 'The Good Samaritan',
    recordIds: ['rec-luke-10-25-37', 'rec-para-luke-10'],
    unlockWhen: flag('heard-yair'),
    order: 1,
  },
  {
    id: 'js-love-commands',
    category: 'scripture',
    title: 'The two great commands',
    summary: 'Deuteronomy 6:5 and Leviticus 19:18',
    recordIds: ['rec-hist-love-commands', 'rec-deut-6-5', 'rec-lev-19-18', 'rec-lev-19-34'],
    unlockWhen: flag('heard-hanan-law'),
    order: 2,
  },

  // Themes
  {
    id: 'jt-neighbor',
    category: 'themes',
    title: 'Who acted as a neighbor?',
    summary: 'Turning the question around',
    recordIds: ['rec-interp-neighbor', 'rec-interp-fair-reading'],
    unlockWhen: flag('seen:scripture-connection'),
    order: 1,
  },
  {
    id: 'jt-mercy',
    category: 'themes',
    title: 'Mercy that costs something',
    summary: 'Love that acts',
    recordIds: ['rec-interp-mercy-cost'],
    unlockWhen: flag('seen:scripture-connection'),
    order: 2,
  },
  {
    id: 'jt-courage',
    category: 'themes',
    title: 'Courage and fear',
    summary: 'When helping feels risky',
    recordIds: ['rec-interp-fear'],
    unlockWhen: { type: 'choiceMade', choice: 'choice-traveler' },
    order: 3,
  },
  {
    id: 'jt-readings',
    category: 'themes',
    title: 'How Christians have read the story',
    summary: 'More than one way of reading',
    recordIds: ['rec-interp-augustine'],
    unlockWhen: flag('seen:scripture-connection'),
    order: 4,
  },

  // Maps
  {
    id: 'jm-route',
    category: 'maps',
    title: 'The route down',
    summary: 'From the east gate to Jericho',
    recordIds: ['rec-map'],
    unlockWhen: {
      type: 'any',
      of: [
        { type: 'hasItem', item: 'map' },
        { type: 'visited', scene: 'jericho' },
      ],
    },
    order: 1,
  },
];
