import type { ChapterInput } from '@/domain/chapter';

/**
 * Everyone the player talks to in this chapter is FICTIONAL, with ordinary
 * Greek names of the period.
 *
 * Philemon, Tychicus and Onesimus are real people named in the New Testament
 * (Philemon 1–2, 10; Colossians 4:7–9). They appear only at the evening
 * gathering, and only as silent figures: they have no dialogue, no invented
 * words, and cannot be talked to or controlled. Nothing about how they looked
 * is known; their appearance here is generic. Paul never appears: his words
 * reach the player only through Scripture references and labelled paraphrase.
 */
export const CHARACTERS: ChapterInput['characters'] = [
  {
    id: 'ammia',
    name: 'Ammia',
    role: 'Your grandmother, a dyer of red wool',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-ammia',
    appearance: {
      skin: '#a8744c',
      hair: '#3a2c22',
      robe: '#7a3228',
      accent: '#e2c27a',
      headwear: 'veil',
      headwearColor: '#e8dcc0',
      beard: false,
      build: 'elder',
      carry: 'basket',
    },
  },
  {
    id: 'kallias',
    name: 'Kallias',
    role: 'Ammia’s former apprentice',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-kallias',
    appearance: {
      skin: '#b07a50',
      hair: '#2a1c12',
      robe: '#8a6a4a',
      accent: '#9a2e28',
      headwear: 'none',
      headwearColor: '#8a6a4a',
      beard: false,
      build: 'adult',
      carry: 'none',
    },
  },
  {
    id: 'zenon',
    name: 'Zenon',
    role: 'A scribe who writes and reads letters',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-zenon',
    appearance: {
      skin: '#9a6a45',
      hair: '#3a3028',
      robe: '#e6dcc4',
      accent: '#35527a',
      headwear: 'none',
      headwearColor: '#e6dcc4',
      beard: true,
      build: 'adult',
      carry: 'tablets',
    },
  },
  {
    id: 'attalos',
    name: 'Attalos',
    role: 'A mule driver on the Laodicea road',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-attalos',
    appearance: {
      skin: '#8a5a38',
      hair: '#1f1611',
      robe: '#6b5a3a',
      accent: '#c9a45a',
      headwear: 'wrap',
      headwearColor: '#c9b48a',
      beard: true,
      build: 'adult',
      carry: 'bundle',
    },
  },
  {
    id: 'tatia',
    name: 'Tatia',
    role: 'A fuller who cleans and finishes cloth',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-tatia',
    appearance: {
      skin: '#b8845a',
      hair: '#2a1a12',
      robe: '#d8d0b8',
      accent: '#5f7438',
      headwear: 'scarf',
      headwearColor: '#9a8a6a',
      beard: false,
      build: 'adult',
      carry: 'basket',
    },
  },
  {
    id: 'menandros',
    name: 'Menandros',
    role: 'A potter',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-menandros',
    appearance: {
      skin: '#a0704a',
      hair: '#2a1a10',
      robe: '#8c5231',
      accent: '#e2c170',
      headwear: 'band',
      headwearColor: '#5a3a22',
      beard: true,
      build: 'adult',
      carry: 'jar',
    },
  },
  {
    id: 'nikon',
    name: 'Nikon',
    role: 'Overseer of the dye works by the bridge',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-nikon',
    appearance: {
      skin: '#9a6040',
      hair: '#4a3a30',
      robe: '#3f5f8f',
      accent: '#d9b25f',
      headwear: 'none',
      headwearColor: '#3f5f8f',
      beard: true,
      build: 'adult',
      carry: 'none',
    },
  },
  {
    id: 'chrysis',
    name: 'Chrysis',
    role: 'An enslaved worker at the dye works',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-chrysis',
    appearance: {
      skin: '#8f5f3f',
      hair: '#1a1210',
      robe: '#7a6a58',
      accent: '#6a2a4f',
      headwear: 'scarf',
      headwearColor: '#6a5a48',
      beard: false,
      build: 'adult',
      carry: 'none',
    },
  },
  {
    id: 'hermon',
    name: 'Hermon',
    role: 'An old weaver of the assembly',
    fictional: true,
    biblicalFigure: false,
    appearance: {
      skin: '#9a6a45',
      hair: '#d8d0c0',
      robe: '#5f6f3a',
      accent: '#c9a45a',
      headwear: 'none',
      headwearColor: '#5f6f3a',
      beard: true,
      build: 'elder',
      carry: 'none',
    },
  },
  {
    id: 'melitta',
    name: 'Melitta',
    role: 'A baker’s wife of the assembly',
    fictional: true,
    biblicalFigure: false,
    appearance: {
      skin: '#b07a50',
      hair: '#2a1a12',
      robe: '#35527a',
      accent: '#e8d49a',
      headwear: 'veil',
      headwearColor: '#d9b25f',
      beard: false,
      build: 'adult',
      carry: 'bread',
    },
  },

  // ── People named in the New Testament: silent, never controlled ────────
  {
    id: 'philemon',
    name: 'Philemon',
    role: 'Host of the assembly in his house (Philemon 1–2)',
    fictional: false,
    biblicalFigure: true,
    journalEntry: 'jp-philemon',
    appearance: {
      skin: '#a8744c',
      hair: '#3a2c22',
      robe: '#e8dcc0',
      accent: '#7a3228',
      headwear: 'none',
      headwearColor: '#e8dcc0',
      beard: true,
      build: 'adult',
      carry: 'none',
    },
  },
  {
    id: 'tychicus',
    name: 'Tychicus',
    role: 'Carrier of the letter (Colossians 4:7–8)',
    fictional: false,
    biblicalFigure: true,
    journalEntry: 'jp-tychicus',
    appearance: {
      skin: '#9a6040',
      hair: '#2a1a10',
      robe: '#6f5a3a',
      accent: '#c9a45a',
      headwear: 'wrap',
      headwearColor: '#c9b48a',
      beard: true,
      build: 'adult',
      carry: 'scroll-case',
    },
  },
  {
    id: 'onesimus',
    name: 'Onesimus',
    role: '“One of you” (Colossians 4:9)',
    fictional: false,
    biblicalFigure: true,
    journalEntry: 'jp-onesimus',
    appearance: {
      skin: '#8a5a38',
      hair: '#1f1611',
      robe: '#8b7a5a',
      accent: '#5a4a3a',
      headwear: 'none',
      headwearColor: '#8b7a5a',
      beard: false,
      build: 'adult',
      carry: 'none',
    },
  },
];
