import type { Condition } from '@/domain/conditions';
import type { ChapterInput } from '@/domain/chapter';

const flag = (name: string): Condition => ({ type: 'flag', flag: name });
const visited = (scene: string): Condition => ({ type: 'visited', scene });
const solved = (puzzle: string): Condition => ({ type: 'puzzleSolved', puzzle });
const any = (...of: Condition[]): Condition => ({ type: 'any', of });

/**
 * The journal. Every entry is a list of labelled ContentRecords, so the
 * journal always shows whether a paragraph is Scripture, paraphrase,
 * history, reconstruction, interpretation or story.
 */
export const JOURNAL: ChapterInput['journal'] = [
  // ── People (fictional: unlocked on meeting) ─────────────────────────────
  {
    id: 'jp-ammia',
    category: 'people',
    title: 'Ammia',
    summary: 'Your grandmother, a dyer',
    recordIds: ['rec-p-ammia'],
    characterId: 'ammia',
    order: 1,
  },
  {
    id: 'jp-kallias',
    category: 'people',
    title: 'Kallias',
    summary: 'Ammia’s former apprentice',
    recordIds: ['rec-p-kallias'],
    characterId: 'kallias',
    order: 2,
  },
  {
    id: 'jp-zenon',
    category: 'people',
    title: 'Zenon',
    summary: 'A scribe',
    recordIds: ['rec-p-zenon', 'rec-hist-scribes'],
    characterId: 'zenon',
    order: 3,
  },
  {
    id: 'jp-attalos',
    category: 'people',
    title: 'Attalos',
    summary: 'A mule driver',
    recordIds: ['rec-p-attalos'],
    characterId: 'attalos',
    order: 4,
  },
  {
    id: 'jp-tatia',
    category: 'people',
    title: 'Tatia',
    summary: 'A fuller',
    recordIds: ['rec-p-tatia'],
    characterId: 'tatia',
    order: 5,
  },
  {
    id: 'jp-menandros',
    category: 'people',
    title: 'Menandros',
    summary: 'A potter',
    recordIds: ['rec-p-menandros'],
    characterId: 'menandros',
    order: 6,
  },
  {
    id: 'jp-nikon',
    category: 'people',
    title: 'Nikon',
    summary: 'Overseer of the dye works',
    recordIds: ['rec-p-nikon'],
    characterId: 'nikon',
    order: 7,
  },
  {
    id: 'jp-chrysis',
    category: 'people',
    title: 'Chrysis',
    summary: 'An enslaved worker at the dye works',
    recordIds: ['rec-p-chrysis', 'rec-hist-slavery'],
    characterId: 'chrysis',
    order: 8,
  },
  {
    id: 'jp-melitta',
    category: 'people',
    title: 'Melitta',
    summary: 'A baker’s wife, and Chrysis’s sister',
    recordIds: ['rec-p-melitta'],
    characterId: 'melitta',
    order: 12,
  },
  // People named in the New Testament: unlocked when you see them.
  {
    id: 'jp-philemon',
    category: 'people',
    title: 'Philemon',
    summary: 'Named in the New Testament',
    recordIds: ['rec-hist-who', 'rec-phm'],
    unlockWhen: flag('saw-carriers'),
    order: 9,
  },
  {
    id: 'jp-tychicus',
    category: 'people',
    title: 'Tychicus',
    summary: 'Named in the New Testament',
    recordIds: ['rec-col-4-7-9', 'rec-eph-6-21', 'rec-hist-carriers'],
    unlockWhen: flag('saw-carriers'),
    order: 10,
  },
  {
    id: 'jp-onesimus',
    category: 'people',
    title: 'Onesimus',
    summary: 'Named in the New Testament',
    recordIds: ['rec-col-4-7-9', 'rec-interp-onesimus', 'rec-interp-later-onesimus'],
    unlockWhen: flag('saw-carriers'),
    order: 11,
  },

  // ── Places ─────────────────────────────────────────────────────────────
  {
    id: 'jpl-colossae',
    category: 'places',
    title: 'Colossae',
    summary: 'A wool town in the Lycus valley',
    recordIds: ['rec-pl-street', 'rec-hist-lycus', 'rec-hist-colossae-site'],
    unlockWhen: visited('colossae-street'),
    order: 1,
  },
  {
    id: 'jpl-workshop',
    category: 'places',
    title: 'Ammia’s workshop',
    summary: 'Madder red and wet wool',
    recordIds: ['rec-pl-workshop', 'rec-hist-wool'],
    unlockWhen: visited('ammia-workshop'),
    order: 2,
  },
  {
    id: 'jpl-road',
    category: 'places',
    title: 'The Laodicea road',
    summary: 'Down the valley by the milestones',
    recordIds: ['rec-rec-road', 'rec-hist-roads'],
    unlockWhen: visited('lycus-road'),
    order: 3,
  },
  {
    id: 'jpl-hierapolis',
    category: 'places',
    title: 'The white cliffs of Hierapolis',
    summary: 'Seen across the valley',
    recordIds: ['rec-hist-hierapolis'],
    unlockWhen: flag('saw-hierapolis'),
    order: 4,
  },
  {
    id: 'jpl-house',
    category: 'places',
    title: 'Philemon’s house',
    summary: 'Where the assembly gathers',
    recordIds: ['rec-pl-house', 'rec-rec-house', 'rec-hist-house-church'],
    unlockWhen: visited('philemon-house'),
    order: 5,
  },

  // ── Events ─────────────────────────────────────────────────────────────
  {
    id: 'je-letter',
    category: 'events',
    title: 'A letter in the rain',
    summary: 'From Kallias',
    recordIds: ['rec-e-letter'],
    order: 1,
  },
  {
    id: 'je-answer',
    category: 'events',
    title: 'Ammia’s answer',
    summary: 'Written in your hand',
    recordIds: ['rec-e-answer'],
    unlockWhen: flag('ammia-letter-written'),
    order: 2,
  },
  {
    id: 'je-bundle',
    category: 'events',
    title: 'The mule driver’s bundle',
    summary: 'A letter with no name',
    recordIds: ['rec-e-bundle'],
    order: 3,
  },
  {
    id: 'je-road',
    category: 'events',
    title: 'The dye works by the bridge',
    summary: 'Kallias',
    recordIds: ['rec-e-road'],
    unlockWhen: flag('read-to-kallias'),
    order: 4,
  },
  {
    id: 'je-hiding',
    category: 'events',
    title: 'Kallias runs',
    summary: 'Down to the riverbank',
    recordIds: ['rec-e-hiding'],
    unlockWhen: { type: 'puzzleSolved', puzzle: 'p-hiding' },
    order: 6,
  },
  {
    id: 'je-message',
    category: 'events',
    title: 'Words for Melitta',
    summary: 'A message from Chrysis',
    recordIds: ['rec-e-message'],
    order: 7,
  },
  {
    id: 'je-gathering',
    category: 'events',
    title: 'The letters read aloud',
    summary: 'At Philemon’s house',
    recordIds: ['rec-e-gathering', 'rec-pl-house'],
    order: 5,
  },

  // ── History & culture ──────────────────────────────────────────────────
  {
    id: 'jh-letters',
    category: 'history',
    title: 'How a letter was made',
    summary: 'Pattern, papyrus and wax',
    recordIds: ['rec-hist-letter-form', 'rec-hist-materials'],
    unlockWhen: any(flag('learned-letter-form'), solved('p-sheets')),
    order: 1,
  },
  {
    id: 'jh-scribes',
    category: 'history',
    title: 'Scribes and signatures',
    summary: '“With my own hand”',
    recordIds: ['rec-hist-scribes', 'rec-rom-16-22', 'rec-own-hand'],
    unlockWhen: solved('p-sheets'),
    order: 2,
  },
  {
    id: 'jh-carriers',
    category: 'history',
    title: 'How letters travelled',
    summary: 'With whoever was going',
    recordIds: ['rec-hist-carriers'],
    unlockWhen: flag('heard-the-letters'),
    order: 3,
  },
  {
    id: 'jh-reading',
    category: 'history',
    title: 'Read aloud',
    summary: 'Hearing a letter together',
    recordIds: ['rec-hist-reading', 'rec-1th-5-27', 'rec-rev-1-3'],
    unlockWhen: flag('heard-the-letters'),
    order: 4,
  },
  {
    id: 'jh-dyeing',
    category: 'history',
    title: 'Madder and alum',
    summary: 'How red wool was dyed',
    recordIds: ['rec-hist-dyeing', 'rec-hist-wool'],
    unlockWhen: any(flag('alum-task'), flag('saw-spoiled-wool')),
    order: 5,
  },
  {
    id: 'jh-slavery',
    category: 'history',
    title: 'Slavery in the Roman world',
    summary: 'Owned, hired and freed',
    recordIds: ['rec-hist-slavery'],
    unlockWhen: any(flag('talked-chrysis'), flag('zenon-story'), flag('heard-the-letters')),
    order: 6,
  },
  {
    id: 'jh-earthquake',
    category: 'history',
    title: 'An earthquake in the valley',
    summary: 'Laodicea, AD 60',
    recordIds: ['rec-hist-earthquake'],
    unlockWhen: visited('lycus-road'),
    order: 7,
  },
  {
    id: 'jh-pliny',
    category: 'history',
    title: 'Another letter asking for mercy',
    summary: 'Pliny to Sabinianus',
    recordIds: ['rec-hist-pliny'],
    unlockWhen: flag('seen:scripture-connection'),
    order: 8,
  },

  // ── Scripture ──────────────────────────────────────────────────────────
  {
    id: 'js-philemon',
    category: 'scripture',
    title: 'The letter to Philemon',
    summary: 'Philemon 1–25',
    recordIds: ['rec-phm', 'rec-para-philemon'],
    unlockWhen: flag('heard-the-letters'),
    order: 1,
  },
  {
    id: 'js-colossians',
    category: 'scripture',
    title: 'The end of Colossians',
    summary: 'Colossians 4:7–18',
    recordIds: ['rec-col-4-7-9', 'rec-col-4-15-16', 'rec-col-4-18', 'rec-para-col-4'],
    unlockWhen: flag('heard-the-letters'),
    order: 2,
  },
  {
    id: 'js-epaphras',
    category: 'scripture',
    title: 'Epaphras, one of their own',
    summary: 'Colossians 1:7; 2:1; 4:12–13',
    recordIds: ['rec-epaphras', 'rec-col-2-1'],
    unlockWhen: flag('heard-the-letters'),
    order: 3,
  },

  // ── Themes ─────────────────────────────────────────────────────────────
  {
    id: 'jt-reconciliation',
    category: 'themes',
    title: 'A letter read in front of everyone',
    summary: 'What reconciliation asks',
    recordIds: ['rec-interp-reconciliation'],
    unlockWhen: flag('seen:scripture-connection'),
    order: 1,
  },
  {
    id: 'jt-slavery',
    category: 'themes',
    title: 'What do these letters say about slavery?',
    summary: 'Hard passages, painful history',
    recordIds: [
      'rec-interp-slavery',
      'rec-col-3-22',
      'rec-col-3-11',
      'rec-gal-3-28',
      'rec-1co-7-21',
    ],
    unlockWhen: flag('seen:scripture-connection'),
    order: 2,
  },
  {
    id: 'jt-open',
    category: 'themes',
    title: 'Questions still open',
    summary: 'Onesimus, the prison, the authors',
    recordIds: [
      'rec-interp-onesimus',
      'rec-interp-prison',
      'rec-interp-authorship',
      'rec-interp-laodicea-letter',
    ],
    unlockWhen: flag('seen:scripture-connection'),
    order: 3,
  },
];
