import type { ChapterInput } from '@/domain/chapter';

/**
 * Sources for Chapter 4. Every entry was retrieved on 2026-09-25 by an AI
 * research assistant and checked against the specific claim it supports
 * (claim-by-claim notes: docs/research/letter-from-paul-sources.md).
 * `verified: true` records THAT retrieval — a human editor must still confirm
 * each citation before any record is approved.
 */
const ACCESSED = '2026-09-25';
const NOTE =
  'Retrieved and checked by an AI research assistant; awaiting human citation verification.';

type Source = ChapterInput['sources'][number];

const web = (id: string, title: string, code: string): Source => ({
  id,
  title: `World English Bible, ${title}`,
  kind: 'scripture',
  url: `https://ebible.org/eng-web/${code}.htm`,
  accessed: ACCESSED,
  verified: true,
  note: NOTE,
});

const src = (
  id: string,
  kind: Source['kind'],
  title: string,
  url: string,
  locator: string,
  author?: string,
): Source => ({
  id,
  title,
  kind,
  url,
  locator,
  ...(author ? { author } : {}),
  accessed: ACCESSED,
  verified: true,
  note: NOTE,
});

export const LETTER_SOURCES: ChapterInput['sources'] = [
  // ── Scripture: the public-domain World English Bible (eBible.org) ───────
  web('src-lp-web-phm', 'Philemon', 'PHM01'),
  web('src-lp-web-col01', 'Colossians 1', 'COL01'),
  web('src-lp-web-col02', 'Colossians 2', 'COL02'),
  web('src-lp-web-col03', 'Colossians 3', 'COL03'),
  web('src-lp-web-col04', 'Colossians 4', 'COL04'),
  web('src-lp-web-rom16', 'Romans 16', 'ROM16'),
  web('src-lp-web-1co07', '1 Corinthians 7', '1CO07'),
  web('src-lp-web-1co16', '1 Corinthians 16', '1CO16'),
  web('src-lp-web-gal03', 'Galatians 3', 'GAL03'),
  web('src-lp-web-gal06', 'Galatians 6', 'GAL06'),
  web('src-lp-web-eph06', 'Ephesians 6', 'EPH06'),
  web('src-lp-web-1th05', '1 Thessalonians 5', '1TH05'),
  web('src-lp-web-2th03', '2 Thessalonians 3', '2TH03'),
  web('src-lp-web-rev01', 'Revelation 1', 'REV01'),
  web('src-lp-web-rev03', 'Revelation 3', 'REV03'),

  // ── Ancient texts ───────────────────────────────────────────────────────
  src(
    'src-lp-strabo-12',
    'ancient-primary',
    'Strabo, Geography 12.8 (Loeb translation, H. L. Jones), LacusCurtius',
    'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Strabo/12H*.html',
    '12.8.13, 12.8.16',
    'Strabo',
  ),
  src(
    'src-lp-strabo-13',
    'ancient-primary',
    'Strabo, Geography 13.4 (Loeb translation), LacusCurtius',
    'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Strabo/13D*.html',
    '13.4.14',
    'Strabo',
  ),
  src(
    'src-lp-strabo-14',
    'ancient-primary',
    'Strabo, Geography 14.2 (Loeb translation), LacusCurtius',
    'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Strabo/14B*.html',
    '14.2.29 (the “common road” east from Ephesus)',
    'Strabo',
  ),
  src(
    'src-lp-herodotus',
    'ancient-primary',
    'Herodotus, Histories 7.30 (tr. A. D. Godley), Perseus Digital Library',
    'https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.01.0126:book=7:chapter=30',
    '7.30.1',
    'Herodotus',
  ),
  src(
    'src-lp-xenophon',
    'ancient-primary',
    'Xenophon, Anabasis 1.2.6 (tr. C. L. Brownson), Perseus Digital Library',
    'https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.01.0202:book=1:chapter=2:section=6',
    '1.2.6',
    'Xenophon',
  ),
  src(
    'src-lp-pliny-21',
    'ancient-primary',
    'Pliny the Elder, Natural History 21 (Latin), LacusCurtius',
    'https://penelope.uchicago.edu/Thayer/L/Roman/Texts/Pliny_the_Elder/21*.html',
    '21.51 (“flos eius Colossinus”)',
    'Pliny the Elder',
  ),
  src(
    'src-lp-pliny-19',
    'ancient-primary',
    'Pliny the Elder, Natural History 19 (tr. Bostock & Riley), Perseus',
    'https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.02.0137:book=19:chapter=17',
    '19.47 (Bostock & Riley 19.17): madder',
    'Pliny the Elder',
  ),
  src(
    'src-lp-pliny-35',
    'ancient-primary',
    'Pliny the Elder, Natural History 35 (tr. Bostock & Riley), Perseus',
    'https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.02.0137:book=35:chapter=52',
    '35.183–184 (Bostock & Riley 35.52): alumen in dyeing',
    'Pliny the Elder',
  ),
  src(
    'src-lp-stockholm',
    'ancient-primary',
    'The Stockholm Papyrus (tr. E. R. Caley, 1927), Wayback Machine copy',
    'https://web.archive.org/web/20210610064634/http://www.clericus.org/etexts/Stockholm%20Papyrus.htm',
    'Recipes 107, 153 (madder; brightening with alum)',
  ),
  src(
    'src-lp-tacitus',
    'ancient-primary',
    'Tacitus, Annals 14 (Loeb translation), LacusCurtius',
    'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Tacitus/Annals/14A*.html',
    '14.27.1 (year fixed by 14.20)',
    'Tacitus',
  ),
  src(
    'src-lp-orosius',
    'ancient-primary',
    'Orosius, Seven Books of History against the Pagans 7 (tr. I. W. Raymond, 1936)',
    'https://www.attalus.org/translate/orosius7A.html',
    '7.7.12',
    'Orosius',
  ),
  src(
    'src-lp-jerome-chronicle',
    'ancient-primary',
    'Jerome’s Chronicle (translation of Eusebius’ Chronicle), tertullian.org',
    'https://www.tertullian.org/fathers/jerome_chronicle_03_part2.htm',
    'Nero, year 10 (the three cities of Asia)',
    'Jerome',
  ),
  src(
    'src-lp-suetonius',
    'ancient-primary',
    'Suetonius, Life of Augustus (tr. J. C. Rolfe), LacusCurtius',
    'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Suetonius/12Caesars/Augustus*.html',
    'Augustus 49.3',
    'Suetonius',
  ),
  src(
    'src-lp-pliny-letters-en',
    'ancient-primary',
    'Pliny the Younger, Letters (tr. Melmoth, rev. Bosanquet), Project Gutenberg #2811',
    'https://www.gutenberg.org/files/2811/2811-h/2811-h.htm',
    'Letters 9.21 and 9.24 (numbered CIII and CV in this edition)',
    'Pliny the Younger',
  ),
  src(
    'src-lp-pliny-letters-la',
    'ancient-primary',
    'Pliny the Younger, Epistulae 9 (Latin), The Latin Library',
    'https://www.thelatinlibrary.com/pliny.ep9.html',
    '9.21, 9.24',
    'Pliny the Younger',
  ),
  src(
    'src-lp-digest',
    'ancient-primary',
    'Justinian’s Digest, book 21 (Latin), Université Grenoble Alpes',
    'https://droitromain.univ-grenoble-alpes.fr/Corpus/d-21.htm',
    '21.1.17.4 (Ulpian, citing Proculus); 21.1.43.1 (Paulus)',
  ),
  src(
    'src-lp-ignatius',
    'ancient-primary',
    'Ignatius of Antioch, Letter to the Ephesians (ANF translation), New Advent',
    'https://www.newadvent.org/fathers/0104.htm',
    'chapter 1',
    'Ignatius of Antioch',
  ),
  src(
    'src-lp-tertullian',
    'ancient-primary',
    'Tertullian, Against Marcion, book 5 (ANF translation), New Advent',
    'https://www.newadvent.org/fathers/03125.htm',
    '5.17',
    'Tertullian',
  ),

  // ── Places, roads and the region ────────────────────────────────────────
  src(
    'src-lp-wiki-colossae',
    'reference-work',
    'Wikipedia, “Colossae”',
    'https://en.wikipedia.org/wiki/Colossae',
    'Location; History',
  ),
  src(
    'src-lp-wiki-laodicea',
    'reference-work',
    'Wikipedia, “Laodicea on the Lycus”',
    'https://en.wikipedia.org/wiki/Laodicea_on_the_Lycus',
    'History',
  ),
  src(
    'src-lp-holylandphotos',
    'web',
    'Carl Rasmussen, “Colossae”, HolyLandPhotos',
    'https://holylandphotos.org/browse/colossae',
    'Introduction (distances; plans to excavate the mound)',
    'Carl Rasmussen',
  ),
  src(
    'src-lp-bas-colossae',
    'web',
    'L. K. McCormick, “Colossae: A Biblical City of the Classical World”, Biblical Archaeology Society (10 July 2026)',
    'https://www.biblicalarchaeology.org/daily/archaeology-today/colossae-a-biblical-city-of-classical-world/',
    'the 2021 survey and the 2025 necropolis season',
  ),
  src(
    'src-lp-unesco-hierapolis',
    'web',
    'UNESCO World Heritage List 485, Hierapolis-Pamukkale (Wayback Machine copy)',
    'https://web.archive.org/web/2024/https://whc.unesco.org/en/list/485/',
    'Description',
  ),
  src(
    'src-lp-wiki-pamukkale',
    'reference-work',
    'Wikipedia, “Pamukkale”',
    'https://en.wikipedia.org/wiki/Pamukkale',
    'lead; Geology',
  ),
  src(
    'src-lp-french-roads',
    'scholarly',
    'D. H. French, “Pre- and Early-Roman Roads of Asia Minor”, Arkeoloji Dergisi V, pp. 179–187',
    'http://dlir.org/archive/archive/files/arkeoloji_dergisi_v-5_p179-187_6bb72bd981.pdf',
    'section 1 (the milestones of Manius Aquillius); p. 186',
    'D. H. French',
  ),
  src(
    'src-lp-wiki-mile',
    'reference-work',
    'Wikipedia, “Mile”',
    'https://en.wikipedia.org/wiki/Mile',
    'Roman mile',
  ),
  src(
    'src-lp-wiki-milestone',
    'reference-work',
    'Wikipedia, “Milestone”',
    'https://en.wikipedia.org/wiki/Milestone',
    'Roman milestones',
  ),
  src(
    'src-lp-orbis',
    'scholarly',
    'W. Scheidel & E. Meeks, ORBIS: The Stanford Geospatial Network Model of the Roman World (v1 paper, May 2012)',
    'https://orbis.stanford.edu/orbis2012/ORBIS_v1paper_20120501.pdf',
    'p. 20 (travel speeds)',
    'Walter Scheidel and Elijah Meeks',
  ),
  src(
    'src-lp-wiki-cursus',
    'reference-work',
    'Wikipedia, “Cursus publicus”',
    'https://en.wikipedia.org/wiki/Cursus_publicus',
    'lead; Use',
  ),

  // ── Letters: writing, carrying, reading ─────────────────────────────────
  src(
    'src-lp-richards',
    'scholarly',
    'E. Randolph Richards, “Paul and First-Century Letter Writing”, Text & Canon Institute (2024)',
    'https://textandcanon.org/paul-and-first-century-letter-writing/',
    'sections “Writing the letter” and following',
    'E. Randolph Richards',
  ),
  src(
    'src-lp-stowers',
    'scholarly',
    'Review of S. K. Stowers, Letter Writing in Greco-Roman Antiquity, Wisconsin Lutheran Seminary',
    'https://wisluthsem.org/review-letter-writing/',
    'on the prescript and health wish',
  ),
  src(
    'src-lp-wiki-pauline',
    'reference-work',
    'Wikipedia, “Pauline epistles”',
    'https://en.wikipedia.org/wiki/Pauline_epistles',
    'Structure',
  ),
  src(
    'src-lp-wiki-tiro',
    'reference-work',
    'Wikipedia, “Marcus Tullius Tiro”',
    'https://en.wikipedia.org/wiki/Marcus_Tullius_Tiro',
    'lead',
  ),
  src(
    'src-lp-wiki-papyrus',
    'reference-work',
    'Wikipedia, “Papyrus”',
    'https://en.wikipedia.org/wiki/Papyrus',
    'lead',
  ),
  src(
    'src-lp-wiki-wax',
    'reference-work',
    'Wikipedia, “Wax tablet”',
    'https://en.wikipedia.org/wiki/Wax_tablet',
    'lead; history',
  ),
  src(
    'src-lp-wiki-vindolanda',
    'reference-work',
    'Wikipedia, “Vindolanda tablets”',
    'https://en.wikipedia.org/wiki/Vindolanda_tablets',
    'lead',
  ),
  src(
    'src-lp-zair',
    'scholarly',
    'N. Zair, Orthographic Traditions and the Sub-elite in the Roman Empire (Cambridge University Press, 2023)',
    'https://www.cambridge.org/core/product/AA724B0E4F2ED33ADD5671D99B9A85D1/core-reader',
    'on Harris (1989) 259–73',
    'Nicholas Zair',
  ),
  src(
    'src-lp-bmcr',
    'scholarly',
    'Bryn Mawr Classical Review 2019.04.45 (review by Minna Skafte Jensen)',
    'https://bmcr.brynmawr.edu/2019/2019.04.45/',
    'on criticism of Harris',
    'Minna Skafte Jensen',
  ),
  src(
    'src-lp-chapple',
    'scholarly',
    'A. Chapple, “Getting Romans to the Right Romans: Phoebe and the Delivery of Paul’s Letter”, Tyndale Bulletin 62.2 (2011)',
    'https://tyndalebulletin.org/article/29314-getting-romans-to-the-right-romans-phoebe-and-the-delivery-of-paul-s-letter.pdf',
    'pp. 212–213',
    'Allan Chapple',
  ),
  src(
    'src-lp-head',
    'scholarly',
    'P. M. Head, “Onesimus the Letter Carrier and the Initial Reception of Paul’s Letter to Philemon” (Oxford Research Archive preprint)',
    'https://ora.ox.ac.uk/objects/uuid:426281c6-0170-42f0-a7e0-6501f777c6ad/files/md3bb5c88be464b61129d13b3ebf4071c',
    'p. 7 and n. 18–19',
    'Peter M. Head',
  ),

  // ── Houses and gatherings ───────────────────────────────────────────────
  src(
    'src-lp-wiki-dura',
    'reference-work',
    'Wikipedia, “Dura-Europos church”',
    'https://en.wikipedia.org/wiki/Dura-Europos_church',
    'lead; History',
  ),
  src(
    'src-lp-yale-dura',
    'web',
    'L. Prevost, “House call: New study rethinks early Christian landmark”, Yale News (12 August 2024)',
    'https://news.yale.edu/2024/08/12/house-call-new-study-rethinks-early-christian-landmark',
    'the Angelo & Silver study',
  ),
  src(
    'src-lp-ephesus-terrace',
    'web',
    '“Ephesus”, Current World Archaeology',
    'https://www.world-archaeology.com/features/ephesus-4/',
    'the Terrace Houses',
  ),
  src(
    'src-lp-oeaw-terrace',
    'scholarly',
    'Hanghaus 2 in Ephesos: Die Wohneinheiten 1 und 2 (Austrian Academy of Sciences Press)',
    'https://verlag.oeaw.ac.at/produkt/hanghaus-2-in-ephesos-die-wohneinheit-1-und-2/600978',
    'publisher’s description',
  ),
  src(
    'src-lp-wiki-triclinium',
    'reference-work',
    'Wikipedia, “Triclinium”',
    'https://en.wikipedia.org/wiki/Triclinium',
    'lead',
  ),

  // ── Slavery ─────────────────────────────────────────────────────────────
  src(
    'src-lp-wiki-slavery',
    'reference-work',
    'Wikipedia, “Slavery in ancient Rome”',
    'https://en.wikipedia.org/wiki/Slavery_in_ancient_Rome',
    'Demography; Manumission; Peculium; Fugitives',
  ),
  src(
    'src-lp-scheidel',
    'scholarly',
    'W. Scheidel, “Human Mobility in Roman Italy, II: The Slave Population”, Journal of Roman Studies 95 (2005)',
    'https://gwern.net/doc/history/2005-scheidel.pdf',
    'conclusion on numbers',
    'Walter Scheidel',
  ),
  src(
    'src-lp-daly',
    'reference-work',
    'J. P. Daly, “Proslavery Writing”, American History through Literature 1820–1870 (encyclopedia.com)',
    'https://www.encyclopedia.com/arts/culture-magazines/proslavery-writing',
    'on Paul’s letters and the Fugitive Slave Law',
    'John Patrick Daly',
  ),
  src(
    'src-lp-beavis',
    'scholarly',
    'M. A. Beavis, “Early Christian Slavery, Early Christian Slaves”, Bible and Interpretation (2024)',
    'https://bibleinterp.arizona.edu/articles/early-christian-slavery-early-christian-slaves',
    'on Onesimus and on the use of the New Testament to uphold slavery',
    'Mary Ann Beavis',
  ),

  // ── The letters: people, dates, open questions ──────────────────────────
  src(
    'src-lp-wiki-philemon',
    'reference-work',
    'Wikipedia, “Epistle to Philemon”',
    'https://en.wikipedia.org/wiki/Epistle_to_Philemon',
    'Authorship; Composition; Interpretation; Themes',
  ),
  src(
    'src-lp-usccb-philemon',
    'reference-work',
    'New American Bible (Revised Edition), introduction to Philemon, USCCB',
    'https://bible.usccb.org/bible/philemon/0',
    'introduction',
  ),
  src(
    'src-lp-fuller',
    'web',
    '“Paul and Philemon”, Fuller Theological Seminary',
    'https://www.fuller.edu/next-faithful-step/resources/paul-and-philemon/',
    'on an Ephesian imprisonment',
  ),
  src(
    'src-lp-tolmie-2025',
    'scholarly',
    'D. F. Tolmie, “The origin and development of the amicus domini hypothesis in Philemon research”, LitNet Akademies (2025)',
    'https://www.litnet.co.za/the-origin-and-development-of-the-amicus-domini-hypothesis-in-philemon-research/',
    'overview of the hypothesis, its history and its critics',
    'D. F. Tolmie',
  ),
  src(
    'src-lp-tolmie-2019',
    'scholarly',
    'D. F. Tolmie, on the history of interpretation of Philemon, Acta Theologica (2019), SciELO',
    'https://scielo.org.za/scielo.php?script=sci_arttext&pid=S1015-87582019000200007',
    'section 3, “Onesimus as a pawn in the abolitionism debate”',
    'D. F. Tolmie',
  ),
  src(
    'src-lp-white',
    'scholarly',
    'J. White, “Who Was Philemon, What Did Paul Want from Him, and Why?”, Themelios 49.3 (2024)',
    'https://www.thegospelcoalition.org/themelios/article/who-was-philemon-what-did-paul-want-from-him-and-why/',
    'on Pliny’s letter to Sabinianus',
    'Joel White',
  ),
  src(
    'src-lp-wiki-onesimus',
    'reference-work',
    'Wikipedia, “Onesimus”',
    'https://en.wikipedia.org/wiki/Onesimus',
    'name; later identification',
  ),
  src(
    'src-lp-knox',
    'web',
    'Kirkus review of John Knox, Philemon among the Letters of Paul',
    'https://www.kirkusreviews.com/book-reviews/a/john-knox-5/philemon-among-the-letters-of-paul/',
    'review',
  ),
  src(
    'src-lp-wiki-colossians',
    'reference-work',
    'Wikipedia, “Epistle to the Colossians”',
    'https://en.wikipedia.org/wiki/Epistle_to_the_Colossians',
    'Authorship; date',
  ),
  src(
    'src-lp-catholic-colossians',
    'reference-work',
    'Catholic Encyclopedia (1908), “Epistle to the Colossians”, New Advent',
    'https://www.newadvent.org/cathen/04131b.htm',
    'on the names shared with Philemon',
  ),
  src(
    'src-lp-wiki-laodiceans',
    'reference-work',
    'Wikipedia, “Epistle to the Laodiceans”',
    'https://en.wikipedia.org/wiki/Epistle_to_the_Laodiceans',
    'Mention in Colossians 4:16; the Latin epistle',
  ),
  src(
    'src-lp-wiki-nympha',
    'reference-work',
    'Wikipedia, “Nympha of Laodicea”',
    'https://en.wikipedia.org/wiki/Nympha_of_Laodicea',
    'the textual variant',
  ),
];
