import type { ChapterInput } from '@/domain/chapter';

/**
 * Source catalogue for educational claims. Every entry below was retrieved
 * and checked against the specific claim it supports by an AI research
 * assistant on 2026-09-24 (see docs/research/source-verification.md for the
 * claim-by-claim notes). `verified: true` records THAT retrieval — a human
 * editor must still confirm citations before any record is approved.
 */
const ACCESSED = '2026-09-24';
const NOTE =
  'Retrieved and checked by an AI research assistant; awaiting human citation verification.';

export const SOURCES: ChapterInput['sources'] = [
  // ── Scripture (public-domain World English Bible, eBible.org) ─────────
  {
    id: 'src-web-luk10',
    title: 'World English Bible, Luke 10',
    kind: 'scripture',
    url: 'https://ebible.org/eng-web/LUK10.htm',
    accessed: ACCESSED,
    verified: true,
    note: NOTE,
  },
  {
    id: 'src-web-luk09',
    title: 'World English Bible, Luke 9',
    kind: 'scripture',
    url: 'https://ebible.org/eng-web/LUK09.htm',
    accessed: ACCESSED,
    verified: true,
    note: NOTE,
  },
  {
    id: 'src-web-jhn04',
    title: 'World English Bible, John 4',
    kind: 'scripture',
    url: 'https://ebible.org/eng-web/JHN04.htm',
    accessed: ACCESSED,
    verified: true,
    note: NOTE,
  },
  {
    id: 'src-web-mat20',
    title: 'World English Bible, Matthew 20',
    kind: 'scripture',
    url: 'https://ebible.org/eng-web/MAT20.htm',
    accessed: ACCESSED,
    verified: true,
    note: NOTE,
  },
  {
    id: 'src-web-lev19',
    title: 'World English Bible, Leviticus 19',
    kind: 'scripture',
    url: 'https://ebible.org/eng-web/LEV19.htm',
    accessed: ACCESSED,
    verified: true,
    note: NOTE,
  },
  {
    id: 'src-web-lev14',
    title: 'World English Bible, Leviticus 14',
    kind: 'scripture',
    url: 'https://ebible.org/eng-web/LEV14.htm',
    accessed: ACCESSED,
    verified: true,
    note: NOTE,
  },
  {
    id: 'src-web-deu06',
    title: 'World English Bible, Deuteronomy 6',
    kind: 'scripture',
    url: 'https://ebible.org/eng-web/DEU06.htm',
    accessed: ACCESSED,
    verified: true,
    note: NOTE,
  },
  {
    id: 'src-web-deu34',
    title: 'World English Bible, Deuteronomy 34',
    kind: 'scripture',
    url: 'https://ebible.org/eng-web/DEU34.htm',
    accessed: ACCESSED,
    verified: true,
    note: NOTE,
  },
  {
    id: 'src-web-jos15',
    title: 'World English Bible, Joshua 15 and 18',
    kind: 'scripture',
    url: 'https://ebible.org/eng-web/JOS15.htm',
    accessed: ACCESSED,
    verified: true,
    note: NOTE,
  },
  {
    id: 'src-web-isa01',
    title: 'World English Bible, Isaiah 1',
    kind: 'scripture',
    url: 'https://ebible.org/eng-web/ISA01.htm',
    accessed: ACCESSED,
    verified: true,
    note: NOTE,
  },
  {
    id: 'src-web-mrk12',
    title: 'World English Bible, Mark 12',
    kind: 'scripture',
    url: 'https://ebible.org/eng-web/MRK12.htm',
    accessed: ACCESSED,
    verified: true,
    note: NOTE,
  },
  {
    id: 'src-web-copyright',
    title: 'eBible.org — World English Bible copyright statement',
    kind: 'web',
    url: 'https://ebible.org/eng-web/copyright.htm',
    accessed: ACCESSED,
    verified: true,
    note: 'States the WEB is in the public domain; "World English Bible" is a trademark.',
  },
  {
    id: 'src-sblgnt-luk10',
    title: 'SBL Greek New Testament, Luke 10 (CC BY 4.0)',
    kind: 'scripture',
    url: 'https://ebible.org/grcsbl/LUK10.htm',
    accessed: ACCESSED,
    verified: true,
    note: 'Greek πανδοχεῖον (inn) in 10:34; κτῆνος (animal) in 10:34.',
  },

  // ── Ancient sources ────────────────────────────────────────────────────
  {
    id: 'src-josephus-war-4',
    title: 'Josephus, The Jewish War 4.451–475 (Whiston translation)',
    kind: 'ancient-primary',
    author: 'Flavius Josephus',
    locator: 'Book 4, §§451–475 (Whiston 4.8.2–3)',
    url: 'https://www.gutenberg.org/cache/epub/2850/pg2850.txt',
    accessed: ACCESSED,
    verified: true,
    note: 'Describes Jericho’s spring, palms and balsam, its mild climate (4.473), and 150 stadia to Jerusalem across desert, stony country (4.474).',
  },
  {
    id: 'src-strabo-16',
    title: 'Strabo, Geography 16.2.40–41 (LacusCurtius)',
    kind: 'ancient-primary',
    author: 'Strabo',
    locator: '16.2.40–41',
    url: 'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Strabo/16B*.html',
    accessed: ACCESSED,
    verified: true,
    note: 'Mentions robbers’ strongholds on the passes to Jericho destroyed by Pompey (63 BC); describes Jericho’s palms and balsam.',
  },
  {
    id: 'src-jerome-108',
    title: 'Jerome, Letter 108 §12 (NPNF), New Advent',
    kind: 'ancient-primary',
    author: 'Jerome',
    locator: 'Letter 108.12 (AD 404)',
    url: 'https://www.newadvent.org/fathers/3001108.htm',
    accessed: ACCESSED,
    verified: true,
    note: 'Calls Adummim “the place of blood” because of frequent attacks — a much later (5th-century) description.',
  },
  {
    id: 'src-hippocrates-ulcers',
    title: 'Hippocrates, On Ulcers (tr. F. Adams), Internet Classics Archive',
    kind: 'ancient-primary',
    url: 'https://classics.mit.edu/Hippocrates/ulcers.mb.txt',
    accessed: ACCESSED,
    verified: true,
    note: 'Advises wetting wounds with wine and applying cloths wetted in wine and oil.',
  },
  {
    id: 'src-talmud-taanit-27a',
    title: 'Babylonian Talmud, Ta’anit 27a (Sefaria)',
    kind: 'ancient-primary',
    url: 'https://www.sefaria.org/Taanit.27a',
    accessed: ACCESSED,
    verified: true,
    note: 'Later rabbinic tradition (compiled c. AD 500) that half of each priestly watch came from Jericho. Reliability debated.',
  },
  {
    id: 'src-augustine-qe',
    title:
      'M. Higton, “Boldness and Reserve: A Lesson from St. Augustine” (quoting Quaestiones Evangeliorum 2.19)',
    kind: 'scholarly',
    url: 'https://mikehigton.webspace.durham.ac.uk/wp-content/uploads/sites/193/2021/05/2003-boldness-and-reserve.pdf',
    accessed: ACCESSED,
    verified: true,
    note: 'Quotes Augustine’s allegorical reading of the parable.',
  },
  {
    id: 'src-augustine-doctrine',
    title: 'Augustine, On Christian Doctrine 1.30.31 (NPNF), New Advent',
    kind: 'ancient-primary',
    author: 'Augustine of Hippo',
    locator: '1.30.31',
    url: 'https://www.newadvent.org/fathers/12021.htm',
    accessed: ACCESSED,
    verified: true,
    note: 'Augustine’s plain moral reading: every person is our neighbor.',
  },

  // ── Modern scholarship and reference ───────────────────────────────────
  {
    id: 'src-roll-roads',
    title: 'I. Roll, “The Roman Road System in Judaea,” Jerusalem Cathedra 3 (1983)',
    kind: 'scholarly',
    author: 'Israel Roll',
    url: 'https://milestones.kinneret.ac.il/wp-content/uploads/2018/02/the_roman_road_system_in_judea2.pdf',
    accessed: ACCESSED,
    verified: true,
    note: 'Roman road-building in Judaea largely followed the revolt of AD 66–70; earlier roads are poorly known.',
  },
  {
    id: 'src-ryan-scjr',
    title:
      'M. Ryan, “Revisiting the Parable of the Good Samaritan,” Studies in Christian-Jewish Relations 16 (2021)',
    kind: 'scholarly',
    author: 'Maurice Ryan',
    url: 'https://ejournals.bc.edu/index.php/scjr/article/download/13987/10613/29105',
    accessed: ACCESSED,
    verified: true,
    note: 'Relations between Jews and Samaritans “strained, but not broken”; warns against readings that stereotype priests and Levites.',
  },
  {
    id: 'src-wiki-jericho',
    title: 'Wikipedia: Jericho',
    kind: 'reference-work',
    url: 'https://en.wikipedia.org/wiki/Jericho',
    accessed: ACCESSED,
    verified: true,
    note: 'Elevation about 258 m below sea level.',
  },
  {
    id: 'src-wiki-jerusalem',
    title: 'Wikipedia: Jerusalem',
    kind: 'reference-work',
    url: 'https://en.wikipedia.org/wiki/Jerusalem',
    accessed: ACCESSED,
    verified: true,
    note: 'Elevation about 754 m above sea level.',
  },
  {
    id: 'src-wiki-adummim',
    title: 'Wikipedia: Adummim',
    kind: 'reference-work',
    url: 'https://en.wikipedia.org/wiki/Adummim',
    accessed: ACCESSED,
    verified: true,
    note: 'Name from Hebrew for “red”; exact location debated.',
  },
  {
    id: 'src-wiki-wadi-qelt',
    title: 'Wikipedia: Wadi Qelt',
    kind: 'reference-work',
    url: 'https://en.wikipedia.org/wiki/Wadi_Qelt',
    accessed: ACCESSED,
    verified: true,
  },
  {
    id: 'src-wiki-judaean-desert',
    title: 'Wikipedia: Judaean Desert',
    kind: 'reference-work',
    url: 'https://en.wikipedia.org/wiki/Judaean_Desert',
    accessed: ACCESSED,
    verified: true,
    note: 'Rain-shadow desert; flash floods in wadis.',
  },
  {
    id: 'src-dayan-floods',
    title: 'Dayan & Morin (2006), “Flash flood-producing rainstorms over the Dead Sea: A review”',
    kind: 'scholarly',
    url: 'https://cris.huji.ac.il/en/publications/flash-flood-producing-rainstorms-over-the-dead-sea-a-review',
    accessed: ACCESSED,
    verified: true,
  },
  {
    id: 'src-wiki-denarius',
    title: 'Wikipedia: Denarius',
    kind: 'reference-work',
    url: 'https://en.wikipedia.org/wiki/Denarius',
    accessed: ACCESSED,
    verified: true,
  },
  {
    id: 'src-wiki-procuratorial-coins',
    title: 'Wikipedia: Procuratorial coinage of Roman Judaea',
    kind: 'reference-work',
    url: 'https://en.wikipedia.org/wiki/Procuratorial_coinage_of_Roman_Judaea',
    accessed: ACCESSED,
    verified: true,
    note: 'The prutah: small bronze coin minted in Jerusalem.',
  },
  {
    id: 'src-wiki-log-unit',
    title: 'Wikipedia: Log (unit)',
    kind: 'reference-work',
    url: 'https://en.wikipedia.org/wiki/Log_(unit)',
    accessed: ACCESSED,
    verified: true,
    note: 'Modern volume estimates vary (roughly 0.3 L to over 0.5 L).',
  },
  {
    id: 'src-wiki-inn-good-samaritan',
    title: 'Wikipedia: Inn of the Good Samaritan',
    kind: 'reference-work',
    url: 'https://en.wikipedia.org/wiki/Inn_of_the_Good_Samaritan',
    accessed: ACCESSED,
    verified: true,
    note: 'A traditional site; the present building dates from 1903.',
  },
  {
    id: 'src-wiki-gerizim',
    title: 'Wikipedia: Mount Gerizim',
    kind: 'reference-work',
    url: 'https://en.wikipedia.org/wiki/Mount_Gerizim',
    accessed: ACCESSED,
    verified: true,
  },
];
