import type { ChapterInput } from '@/domain/chapter';

/**
 * Everyone you meet in this chapter is FICTIONAL. Names are ordinary names
 * of the period. Jesus does not appear as a character, and nobody in the
 * teacher's boat is shown or heard: the player's family boat is one of the
 * "other boats" Mark 4:36 mentions, and learns what happened aboard the
 * teacher's boat only from Scripture, in the Scripture Connection.
 */
export const CHARACTERS: ChapterInput['characters'] = [
  {
    id: 'shelomit',
    name: 'Grandmother Shelomit',
    role: 'Your grandmother, a net-mender',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-shelomit',
    appearance: {
      skin: '#946443',
      hair: '#3a2e26',
      robe: '#5f4a6e',
      accent: '#d9b25f',
      headwear: 'veil',
      headwearColor: '#e8dcc0',
      beard: false,
      build: 'elder',
      carry: 'net',
    },
  },
  {
    id: 'elazar',
    name: 'Uncle Elazar',
    role: 'Master of the family boat',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-elazar',
    appearance: {
      skin: '#8a5634',
      hair: '#1f1611',
      robe: '#3f5f6f',
      accent: '#c9a45a',
      headwear: 'wrap',
      headwearColor: '#d8c8a0',
      beard: true,
      build: 'adult',
      carry: 'oar',
    },
  },
  {
    id: 'tamar',
    name: 'Tamar',
    role: 'Your cousin, a rower',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-tamar',
    appearance: {
      skin: '#9a6440',
      hair: '#1a1210',
      robe: '#8f3f2f',
      accent: '#e2b555',
      headwear: 'scarf',
      headwearColor: '#c96f3b',
      beard: false,
      build: 'adult',
      carry: 'net',
    },
  },
  {
    id: 'yoezer',
    name: 'Yoezer',
    role: 'A hired man on the family boat',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-yoezer',
    appearance: {
      skin: '#7a4a2e',
      hair: '#2a1a10',
      robe: '#6b5a3a',
      accent: '#8a6a4a',
      headwear: 'band',
      headwearColor: '#5a4a3a',
      beard: true,
      build: 'adult',
      carry: 'jar',
    },
  },
  {
    id: 'hanina',
    name: 'Old Hanina',
    role: 'A fisherman who has read the lake for sixty years',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-hanina',
    appearance: {
      skin: '#86583a',
      hair: '#d8d0c0',
      robe: '#7a6a52',
      accent: '#4a5a6a',
      headwear: 'hood',
      headwearColor: '#8b7a5a',
      beard: true,
      build: 'elder',
      carry: 'staff',
    },
  },
  {
    id: 'nikanor',
    name: 'Nikanor',
    role: 'A salt-fish trader from Magdala',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-nikanor',
    appearance: {
      skin: '#a0704a',
      hair: '#2a1a10',
      robe: '#2f5f7f',
      accent: '#e8d49a',
      headwear: 'wrap',
      headwearColor: '#efe6d2',
      beard: true,
      build: 'adult',
      carry: 'basket',
    },
  },
  {
    id: 'shifra',
    name: 'Shifra',
    role: 'A potter’s wife from the hills',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-shifra',
    appearance: {
      skin: '#b07a50',
      hair: '#2a1a12',
      robe: '#556b3a',
      accent: '#e8d49a',
      headwear: 'veil',
      headwearColor: '#d8c8a8',
      beard: false,
      build: 'adult',
      carry: 'basket',
    },
  },
  {
    id: 'ami',
    name: 'Ami',
    role: 'Shifra’s son',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-ami',
    appearance: {
      skin: '#b07a50',
      hair: '#2a1a12',
      robe: '#c9a878',
      accent: '#556b3a',
      headwear: 'none',
      headwearColor: '#c9a878',
      beard: false,
      build: 'child',
    },
  },
  {
    id: 'oded',
    name: 'Oded',
    role: 'Shifra’s brother, a potter',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-oded',
    appearance: {
      skin: '#a8734a',
      hair: '#3a2a1c',
      robe: '#8a7a5c',
      accent: '#b8683e',
      headwear: 'band',
      headwearColor: '#8a2f2f',
      beard: true,
      build: 'adult',
      carry: 'oar',
    },
  },
  {
    id: 'dinah',
    name: 'Dinah',
    role: 'A farmer’s wife, in the crowd',
    fictional: true,
    biblicalFigure: false,
    journalEntry: 'jp-dinah',
    appearance: {
      skin: '#9a6a45',
      hair: '#2a1a10',
      robe: '#7a4b3a',
      accent: '#e3c27a',
      headwear: 'scarf',
      headwearColor: '#d9b25f',
      beard: false,
      build: 'adult',
      carry: 'basket',
    },
  },
  {
    id: 'listener-a',
    name: 'A listener',
    role: 'Someone in the crowd',
    fictional: true,
    biblicalFigure: false,
    appearance: {
      skin: '#8f5f3f',
      hair: '#1f1510',
      robe: '#6f5a3a',
      accent: '#3f6f8f',
      headwear: 'wrap',
      headwearColor: '#d8c8a0',
      beard: true,
      build: 'adult',
    },
  },
  {
    id: 'listener-b',
    name: 'A listener',
    role: 'Someone in the crowd',
    fictional: true,
    biblicalFigure: false,
    appearance: {
      skin: '#a57550',
      hair: '#2a1a10',
      robe: '#3f5f8f',
      accent: '#e8d49a',
      headwear: 'veil',
      headwearColor: '#efe3c8',
      beard: false,
      build: 'adult',
    },
  },
  {
    id: 'listener-c',
    name: 'A listener',
    role: 'Someone in the crowd',
    fictional: true,
    biblicalFigure: false,
    appearance: {
      skin: '#86583a',
      hair: '#d8d0c0',
      robe: '#8b7a5a',
      accent: '#5a4a3a',
      headwear: 'scarf',
      headwearColor: '#e8dcc0',
      beard: true,
      build: 'elder',
      carry: 'staff',
    },
  },
];
