import type { ChapterInput } from '@/domain/chapter';

/**
 * Sources for "A Storm on Galilee". Every entry was retrieved and the claim
 * it supports checked by an AI research assistant on 2026-09-25 (claim-by-
 * claim notes: docs/research/storm-on-galilee-sources.md). `verified: true`
 * records THAT retrieval — a named human editor must still confirm each
 * citation before any record is approved.
 */
const ACCESSED = '2026-09-25';
const NOTE =
  'Retrieved and checked by an AI research assistant; awaiting human citation verification.';

type Source = ChapterInput['sources'][number];

const web = (id: string, title: string, file: string, note?: string): Source => ({
  id,
  title: `World English Bible, ${title}`,
  kind: 'scripture',
  url: `https://ebible.org/eng-web/${file}.htm`,
  accessed: ACCESSED,
  verified: true,
  note: note ?? NOTE,
});

const sblgnt = (id: string, title: string, file: string, note: string): Source => ({
  id,
  title: `SBL Greek New Testament, ${title} (CC BY 4.0)`,
  kind: 'scripture',
  url: `https://ebible.org/grcsbl/${file}.htm`,
  accessed: ACCESSED,
  verified: true,
  note,
});

export const STORM_SOURCES: ChapterInput['sources'] = [
  // ── Scripture (public-domain World English Bible, eBible.org) ─────────
  web('src-web-mrk04', 'Mark 4', 'MRK04', 'Mark 4:1–9 and 4:35–41 read and quoted from this page.'),
  web('src-web-mat08', 'Matthew 8', 'MAT08'),
  web(
    'src-web-luk08',
    'Luke 8',
    'LUK08',
    'Luke 8:22–23 says “lake” and that the storm “came down on the lake.”',
  ),
  web('src-web-mrk05', 'Mark 5', 'MRK05'),
  web(
    'src-web-mrk01',
    'Mark 1',
    'MRK01',
    'Mark 1:16–21 (fishermen, hired servants, Capernaum) and 1:29.',
  ),
  web('src-web-mrk02', 'Mark 2', 'MRK02', 'Mark 2:1–4: the roof removed in Capernaum.'),
  web(
    'src-web-luk05',
    'Luke 5',
    'LUK05',
    'Luke 5:1–11: lake of Gennesaret, washing nets, partners.',
  ),
  web(
    'src-web-mat04',
    'Matthew 4',
    'MAT04',
    'Matthew 4:13 (lived in Capernaum) and 4:18 (casting a net).',
  ),
  web('src-web-mat13', 'Matthew 13', 'MAT13'),
  web('src-web-psa107', 'Psalm 107', 'PSA107'),
  web('src-web-psa089', 'Psalm 89', 'PSA089'),
  web(
    'src-web-jon01',
    'Jonah 1',
    'JON01',
    'Jonah 1:5: cargo thrown overboard; Jonah “fast asleep.”',
  ),
  web('src-web-lev11', 'Leviticus 11', 'LEV11'),
  sblgnt(
    'src-sblgnt-mrk04',
    'Mark 4',
    'MRK04',
    'Mark 4:36 ἄλλα πλοῖα (other boats); 4:37 λαῖλαψ (windstorm); 4:38 ἐν τῇ πρύμνῃ ἐπὶ τὸ προσκεφάλαιον (in the stern, on the cushion).',
  ),
  sblgnt(
    'src-sblgnt-luk08',
    'Luke 8',
    'LUK08',
    'Luke 8:22 λίμνης (lake); 8:23 κατέβη λαῖλαψ ἀνέμου εἰς τὴν λίμνην (a windstorm came down on the lake).',
  ),
  sblgnt('src-sblgnt-mat04', 'Matthew 4', 'MAT04', 'Matthew 4:18 ἀμφίβληστρον (cast net).'),
  sblgnt('src-sblgnt-mat13', 'Matthew 13', 'MAT13', 'Matthew 13:47 σαγήνῃ (dragnet).'),

  // ── Ancient writers ─────────────────────────────────────────────────────
  {
    id: 'src-josephus-war-lake',
    title: 'Josephus, The Jewish War 2.635 and 3.506–521 (Whiston translation)',
    kind: 'ancient-primary',
    author: 'Flavius Josephus',
    locator: '2.635 (Whiston 2.21.8); 3.506–521 (Whiston 3.10.7–8)',
    url: 'https://www.gutenberg.org/cache/epub/2850/pg2850.txt',
    accessed: ACCESSED,
    verified: true,
    note: '2.635: “all the ships that were upon the lake, which were found to be two hundred and thirty… no more than four mariners” in each. 3.506: the lake’s “waters are sweet, and very agreeable for drinking.” 3.516–519: the fertile plain of Gennesar.',
  },
  {
    id: 'src-strabo-16-45',
    title: 'Strabo, Geography 16.2.45 (LacusCurtius)',
    kind: 'ancient-primary',
    author: 'Strabo',
    locator: '16.2.45',
    url: 'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Strabo/16B*.html',
    accessed: ACCESSED,
    verified: true,
    note: '“At the place called Taricheae the lake supplies excellent fish for pickling.” The sentence sits in a passage about asphalt and the Dead Sea; Strabo does not name the lake.',
  },
  {
    id: 'src-tertullian-baptism',
    title: 'Tertullian, On Baptism 12 (ANF, tr. S. Thelwall), New Advent',
    kind: 'ancient-primary',
    author: 'Tertullian',
    locator: 'Chapter 12',
    url: 'https://www.newadvent.org/fathers/0321.htm',
    accessed: ACCESSED,
    verified: true,
    note: '“But that little ship did present a figure of the Church, in that she is disquieted in the sea, that is, in the world, by the waves, that is, by persecutions and temptations.”',
  },
  {
    id: 'src-augustine-sermon-63',
    title: 'Augustine, Sermon 13 on the New Testament [63 Ben.] on Matthew 8:23 (NPNF), New Advent',
    kind: 'ancient-primary',
    author: 'Augustine of Hippo',
    locator: '§§1–3',
    url: 'https://www.newadvent.org/fathers/160313.htm',
    accessed: ACCESSED,
    verified: true,
    note: '§1: “That ship also was a figure of the Church.” §3: “let us not despair; let us awake Christ.”',
  },
  {
    id: 'src-chrysostom-hom28',
    title: 'John Chrysostom, Homily 28 on Matthew (NPNF), New Advent',
    kind: 'ancient-primary',
    author: 'John Chrysostom',
    url: 'https://www.newadvent.org/fathers/200128.htm',
    accessed: ACCESSED,
    verified: true,
    note: '“while the sleep and the outward appearance showed man, the sea and the calm declared Him God.”',
  },
  {
    id: 'src-calvin-harmony',
    title: 'John Calvin, Commentary on a Harmony of the Evangelists (tr. W. Pringle), CCEL',
    kind: 'ancient-primary',
    author: 'John Calvin',
    locator: 'Matthew 8:23–27; Mark 4:35–41; Luke 8:22–25',
    url: 'https://ccel.org/ccel/c/calvin/calcom31/cache/calcom31.txt',
    accessed: ACCESSED,
    verified: true,
    note: '“It is not every kind of fear that is opposed to faith.” Also: “Mark says that other little ships crossed along with him.”',
  },
  {
    id: 'src-strauss-life',
    title:
      'D. F. Strauss, The Life of Jesus Critically Examined §101 (tr. George Eliot), Project Gutenberg',
    kind: 'scholarly',
    author: 'David Friedrich Strauss',
    locator: '§101, “Anecdotes having relation to the sea”',
    url: 'https://www.gutenberg.org/cache/epub/64037/pg64037.txt',
    accessed: ACCESSED,
    verified: true,
    note: 'Rejects the natural explanation and proposes that legend framed the narrative (“how easily legend might come to frame such a narrative”).',
  },
  {
    id: 'src-schweitzer-paulus',
    title: 'A. Schweitzer, The Quest of the Historical Jesus, ch. 5 “Paulus” (tr. W. Montgomery)',
    kind: 'scholarly',
    author: 'Albert Schweitzer',
    locator: 'Chapter V',
    url: 'http://www.earlychristianwritings.com/schweitzer/chapter5.html',
    accessed: ACCESSED,
    verified: true,
    note: 'Summarises Paulus on the storm: “At that moment they gained the shelter of a hill which protected them from the wind.”',
  },

  // ── The lake, its winds, and its boats ────────────────────────────────
  {
    id: 'src-wiki-sea-of-galilee',
    title: 'Wikipedia: Sea of Galilee',
    kind: 'reference-work',
    url: 'https://en.wikipedia.org/wiki/Sea_of_Galilee',
    accessed: ACCESSED,
    verified: true,
    note: 'Length 21 km, width 13 km, max depth 43 m; surface between 215 and 209 m below sea level; between the Golan Heights and the Galilee. Four kinds of fish named by local fishermen.',
  },
  {
    id: 'src-bibleplaces-sea',
    title: 'BiblePlaces.com: Sea of Galilee (T. Bolen)',
    kind: 'web',
    url: 'https://www.bibleplaces.com/seagalilee/',
    accessed: ACCESSED,
    verified: true,
    note: '“Winds funnel through the east-west aligned Galilee hill country and stir up the waters quickly. More violent are the winds that come off the hills of the Golan Heights to the east.”',
  },
  {
    id: 'src-bolen-jp',
    title: 'T. Bolen, “The Sea of Galilee,” Jerusalem Perspective (1989)',
    kind: 'web',
    author: 'Todd Bolen',
    url: 'https://www.jerusalemperspective.com/1476/',
    accessed: ACCESSED,
    verified: true,
    note: '“The most violent storms, however, are caused by the fierce winds which blow off the Golan Heights from the east.” Capernaum harbour more than 800 m long; catfish “not considered kosher because of its lack of scales.”',
  },
  {
    id: 'src-alpert-1982',
    title:
      'P. Alpert et al., “A Model Simulation of the Summer Circulation from the Eastern Mediterranean past Lake Kinneret,” Monthly Weather Review 110 (1982) — abstract via OpenAlex',
    kind: 'scholarly',
    url: 'https://api.openalex.org/works/doi:10.1175/1520-0493(1982)110%3C0994:AMSOTS%3E2.0.CO;2',
    accessed: ACCESSED,
    verified: true,
    note: '“the almost daily development of strong winds and an associated storm on the lake in the afternoon”; the sea-breeze front reaching the warm Kinneret valley.',
  },
  {
    id: 'src-bitan-1981',
    title:
      'A. Bitan, “Lake Kinneret (Sea of Galilee) and its exceptional wind system,” Boundary-Layer Meteorology 21 (1981) — abstract',
    kind: 'scholarly',
    url: 'https://cris.tau.ac.il/en/publications/lake-kinneret-sea-of-galilee-and-its-exceptional-wind-system/',
    accessed: ACCESSED,
    verified: true,
    note: 'A westerly wind from the Mediterranean breeze “plunges towards the lake”; “Late at night, a wind flow develops from the land towards the lake, which combines with the katabatic winds.”',
  },
  {
    id: 'src-saaroni-1998',
    title:
      'H. Saaroni et al., “Easterly Wind Storms over Israel,” Theoretical and Applied Climatology 59 (1998)',
    kind: 'scholarly',
    url: 'https://www.tau.ac.il/~pinhas/papers/1998/Saaroni_et_al_TAC_1998.pdf',
    accessed: ACCESSED,
    verified: true,
    note: 'Easterly storms occur October–May, “strengthening in the morning hours”; night-time land breeze and katabatic winds “contribute to the increasing of easterly winds during the night hours” (p. 70). The paper covers all of Israel.',
  },
  {
    id: 'src-wachsmann-bar-1988',
    title:
      'S. Wachsmann, “The Galilee Boat—2,000-Year-Old Hull Recovered Intact,” BAR 14:5 (1988), reproduced by COJS',
    kind: 'scholarly',
    author: 'Shelley Wachsmann',
    url: 'https://cojs.org/galilee-boat-2000-year-old-hull-recovered-intact-shelley-wachsmann-bar-1405-sepoct-1988/',
    accessed: ACCESSED,
    verified: true,
    note: 'Found January 1986 during a drought; radiocarbon “40 B.C., plus or minus 80 years”; cedar planking and oak frames; “repeatedly repaired”; four rowers and a helmsman; the “pillow” “may have been a sandbag used for ballast.” Wachsmann: “no proof that our boat played any part in these momentous events.”',
  },
  {
    id: 'src-wachsmann-seafaring',
    title: 'S. Wachsmann, “Ancient Seafaring on the Sea of Galilee,” jesusboat.com archive',
    kind: 'scholarly',
    author: 'Shelley Wachsmann',
    url: 'https://www.jesusboat.com/jesusboat-archive/ancient-seafaring-and-the-jesus-boat/',
    accessed: ACCESSED,
    verified: true,
    note: '“8.2 x 2.3 x 1.2 m”; a mast step (“four nail holes and a discoloration”); the Migdal mosaic boat with “a mast, and a furled, square sail” and a quarter rudder.',
  },
  {
    id: 'src-wiki-galilee-boat',
    title: 'Wikipedia: Sea of Galilee Boat',
    kind: 'reference-work',
    url: 'https://en.wikipedia.org/wiki/Sea_of_Galilee_Boat',
    accessed: ACCESSED,
    verified: true,
    note: '“found by brothers Moshe and Yuval Lufan”; “pegged mortise and tenon joints”; “four staggered rowers, and also had a mast.”',
  },
  {
    id: 'src-yigal-allon',
    title: 'Yigal Allon Centre: The Ancient Boat',
    kind: 'museum',
    url: 'https://yigal-allon-centre.org.il/en/the-museum/the-ancient-boat/',
    accessed: ACCESSED,
    verified: true,
    note: 'The museum where the boat is displayed at Kibbutz Ginosar; preserved “for 14 years until 2000.”',
  },
  {
    id: 'src-wiki-square-rig',
    title: 'Wikipedia: Square rig',
    kind: 'reference-work',
    url: 'https://en.wikipedia.org/wiki/Square_rig',
    accessed: ACCESSED,
    verified: true,
    note: 'Classical square sails used “brailing lines which were used to both furl and reef the sail.”',
  },

  // ── Fishing, salting, Capernaum ───────────────────────────────────────
  {
    id: 'src-hanson-fishing',
    title: 'K. C. Hanson, “The Galilean Fishing Economy and the Jesus Tradition,” BTB 27 (1997)',
    kind: 'scholarly',
    author: 'K. C. Hanson',
    url: 'https://www.kchanson.com/ARTICLES/fishing.html',
    accessed: ACCESSED,
    verified: true,
    note: 'Cast net (amphiblêstron) and dragnet (sagênê); Zebedee with sons and hired laborers; a model of state-regulated fishing rights under Antipas, adapted from Egyptian and Syrian evidence; fish “cured and pickled or dried and salted.”',
  },
  {
    id: 'src-myles-fishing',
    title:
      'R. J. Myles, “Fishing for Entrepreneurs in the Sea of Galilee?,” Bible and Interpretation (2019)',
    kind: 'scholarly',
    author: 'Robert J. Myles',
    url: 'https://bibleinterp.arizona.edu/articles/fishing-entrepreneurs-sea-galilee-unmasking-neoliberal-ideology-biblical-interpretation',
    accessed: ACCESSED,
    verified: true,
    note: 'Summarises the debate, including the view that the growing fish trade “gave an economic boost to the local economy.”',
  },
  {
    id: 'src-nun-nets',
    title: 'M. Nun, “‘Let Down Your Nets’,” Jerusalem Perspective 24 (1990)',
    kind: 'scholarly',
    author: 'Mendel Nun',
    url: 'https://www.jerusalemperspective.com/2451/',
    accessed: ACCESSED,
    verified: true,
    note: '“The trammel net is the only net from ancient times that is still used commercially on the Sea of Galilee.” “trammel-net fishing is done at night.” “In Jesus’ time fishing nets were made of linen thread.”',
  },
  {
    id: 'src-franz-fish',
    title: 'G. Franz, “Greatest Fish Stories Ever Told,” Bible and Spade',
    kind: 'web',
    author: 'Gordon Franz',
    url: 'https://www.ldolphin.org/fish-franz.html',
    accessed: ACCESSED,
    verified: true,
    note: 'Trammel nets “are used only at night because the fish can see the nets in daylight.”',
  },
  {
    id: 'src-wiki-magdala',
    title: 'Wikipedia: Magdala',
    kind: 'reference-work',
    url: 'https://en.wikipedia.org/wiki/Magdala',
    accessed: ACCESSED,
    verified: true,
    note: 'Babylonian Talmud name Magdala Nunayya, “Tower of the Fishes”; Tarichaea from Greek tarichos, “although the matter remains disputed.”',
  },
  {
    id: 'src-bas-magdala',
    title:
      'M. Zapata-Meza, “The Fishy Secret to Ancient Magdala’s Economic Growth,” Bible History Daily (2016)',
    kind: 'web',
    author: 'Marcela Zapata-Meza',
    url: 'https://www.biblicalarchaeology.org/daily/archaeology-today/the-fishy-secret-to-ancient-magdalas-economic-growth/',
    accessed: ACCESSED,
    verified: true,
    note: '“about 300 fishing weights”; “The port of Magdala is 700 meters long.”',
  },
  {
    id: 'src-magdala-salted',
    title: 'C. Vilaroig, “The Best Salted Fish,” Magdala.org (2020)',
    kind: 'web',
    url: 'https://www.magdala.org/journal/history-the-best-salted-fish',
    accessed: ACCESSED,
    verified: true,
    note: '“small pools that look like structures designed for salting fish”; identifies Tarichaea with Magdala “as most scholars do.”',
  },
  {
    id: 'src-wiki-capernaum',
    title: 'Wikipedia: Capernaum',
    kind: 'reference-work',
    url: 'https://en.wikipedia.org/wiki/Capernaum',
    accessed: ACCESSED,
    verified: true,
    note: 'Fishing village; “population of about 1,500 in the 1st century AD” (Reed 2002); local black basalt; roofs of “light wooden beams and thatch mixed with mud”; an ancient harbour west of the modern pier.',
  },
  {
    id: 'src-sciencedaily-kosher',
    title:
      'ScienceDaily (2021), on Adler & Lernau, Tel Aviv 48 (2021): non-kosher fish in ancient Judea',
    kind: 'web',
    url: 'https://www.sciencedaily.com/releases/2021/05/210525084317.htm',
    accessed: ACCESSED,
    verified: true,
    note: '“Non-kosher fish bones were mostly absent from Judean settlements dating to the Roman era and later.” (Retrieved through a summarising fetch; spot-check the wording.)',
  },

  // ── Interpretation ────────────────────────────────────────────────────
  {
    id: 'src-black-wp',
    title: 'C. C. Black, “Commentary on Mark 4:35-41,” Working Preacher (2024)',
    kind: 'scholarly',
    author: 'C. Clifton Black',
    url: 'https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-12-2/commentary-on-mark-435-41-6',
    accessed: ACCESSED,
    verified: true,
    note: '“Only Mark refers to ‘other boats … with him’ (4:36c), but that escort fades away.” Psalm 107:23–30 correspondences; the sea as chaos only the Lord can master.',
  },
  {
    id: 'src-skinner-wp',
    title: 'M. Skinner, “Commentary on Mark 4:35-41,” Working Preacher (2018)',
    kind: 'scholarly',
    author: 'Matt Skinner',
    url: 'https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-12-2/commentary-on-mark-435-41-4',
    accessed: ACCESSED,
    verified: true,
    note: '“The intertextual resonances alone do not necessarily mean that Jesus is God, as if the equation were so simple, but clearly he acts with God’s authority.”',
  },
  {
    id: 'src-jacobsen-wp',
    title: 'D. S. Jacobsen, “Commentary on Mark 4:35-41,” Working Preacher (2021)',
    kind: 'scholarly',
    author: 'David Schnasa Jacobsen',
    url: 'https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-12-2/commentary-on-mark-435-41-5',
    accessed: ACCESSED,
    verified: true,
    note: '“though we are in the same storm, we are not necessarily in the same boat.”',
  },
  {
    id: 'src-stamper-wp',
    title: 'M. Stamper, “Commentary on Mark 4:35-41,” Working Preacher (2012)',
    kind: 'scholarly',
    author: 'Meda Stamper',
    url: 'https://www.workingpreacher.org/commentaries/revised-common-lectionary/ordinary-12-2/commentary-on-mark-435-41',
    accessed: ACCESSED,
    verified: true,
    note: '“following Jesus does not guarantee us, as individuals or as a church, a storm-free life.”',
  },
  {
    id: 'src-redd-tgc',
    title: 'S. Redd, “Why Did Jesus Sleep During the Storm?,” The Gospel Coalition (2019)',
    kind: 'web',
    author: 'Scott Redd',
    url: 'https://www.thegospelcoalition.org/article/jesus-sleep-storm/',
    accessed: ACCESSED,
    verified: true,
    note: '“The story of Jonah shares similar elements and language (in its Greek translation) to the one in Mark 4, which suggests Mark is evoking the story.”',
  },
  {
    id: 'src-tshehla-2018',
    title:
      'M. S. Tshehla, “There Were Other Boats Too: A Note on Mark 4:36’s Contribution to Jesus’ Identity in Mark’s Gospel,” Scriptura 116 (2018)',
    kind: 'scholarly',
    author: 'Maarman S. Tshehla',
    url: 'https://scriptura.journals.ac.za/pub/article/view/1338',
    accessed: ACCESSED,
    verified: true,
    note: 'Asks whether the “other boats” intimate Jesus’ “consistent awareness of and openness to ‘others’.”',
  },
  {
    id: 'src-francis-2020',
    title: 'Pope Francis, Homily at the Extraordinary Moment of Prayer (27 March 2020), vatican.va',
    kind: 'web',
    author: 'Pope Francis',
    url: 'https://www.vatican.va/content/francesco/en/homilies/2020/documents/papa-francesco_20200327_omelia-epidemia.html',
    accessed: ACCESSED,
    verified: true,
    note: '“They had not stopped believing in him; in fact, they called on him.”',
  },
  {
    id: 'src-ccc-547',
    title: 'Catechism of the Catholic Church §§547–550, vatican.va',
    kind: 'reference-work',
    url: 'https://www.vatican.va/archive/ENG0015/__P1L.HTM',
    accessed: ACCESSED,
    verified: true,
    note: '§548: miracles “bear witness that he is the Son of God.” These paragraphs do not mention the storm itself.',
  },
  {
    id: 'src-wiki-miracles',
    title: 'Wikipedia: Miracles of Jesus',
    kind: 'reference-work',
    url: 'https://en.wikipedia.org/wiki/Miracles_of_Jesus',
    accessed: ACCESSED,
    verified: true,
    note: '“For many Christians and Muslims, the miracles are believed to be actual historical events. Others, including many liberal Christians, consider these stories to be figurative.” Ehrman: historians can neither affirm nor deny them.',
  },
  {
    id: 'src-hultgren-2009',
    title:
      'A. J. Hultgren, “The Miracle Stories in the Gospels: The Continuing Challenge for Interpreters,” Word & World 29/2 (2009)',
    kind: 'scholarly',
    author: 'Arland J. Hultgren',
    url: 'https://wordandworld.luthersem.edu/wp-content/uploads/pdfs/29-2_Jesus/The%20Miracle%20Stories%20in%20the%20Gospels;%20The%20Continuing%20Challenge%20for%20Interpreters.pdf',
    accessed: ACCESSED,
    verified: true,
    note: 'Surveys views, from Bultmann (nature miracles such as the stilling of the storm judged non-historical) to the recent tendency “to affirm the essential historicity of the miracles of Jesus (even if not all of them).”',
  },
];
